### ISSUE TITLE
Game does not start correctly when loading any 1.5.12+ versions in 1.19

### ISSUE THREAD

**Issue by randomguy132** [Faboslav/friends-and-foes#103]
### Minecraft version information

1.19

### Mod loader information

Forge

### Mod loader version information

41.1.0 (forge)

### Mod version information

1.8.1 for 1.19

### Reproduction Steps

When opening the game it does not load correctly and it sends me a crash report
This also doesn't work with any 1.5.12+ versions of the mod

### Crash Report and latest.log

[latest.log](https://github.com/Faboslav/friends-and-foes/files/11204723/latest.log)
[crash-2023-04-11_14.01.45-fml.txt](https://github.com/Faboslav/friends-and-foes/files/11204732/crash-2023-04-11_14.01.45-fml.txt)

**Comment by Faboslav** [comment]
Will try to test this over the following weekend.

**Comment by Faboslav** [comment]
I dont know how i missed that, but you just need to update your forge version, in the crash file you can see this message:
`Failure message: Mod friendsandfoes requires forge 43.1.0 or above`, can you try to update your forge version to 43.1.0 or above and let me know please?

**Comment by randomguy132** [comment]
that's the problem, I have too many 1.19 exclusive mods I cant update

**Comment by Faboslav** [comment]
Then i believe that you will have to remove Friends&Foes, because sadly newer forge version is a requirement.

**Comment by randomguy132** [comment]
Wait let me trie the mod without any other mod

**Comment by randomguy132** [comment]
yeah it gives me the same error, even without other mods
[crash-2023-04-23_18.04.43-fml.txt](https://github.com/Faboslav/friends-and-foes/files/11305321/crash-2023-04-23_18.04.43-fml.txt)
[latest.log](https://github.com/Faboslav/friends-and-foes/files/11305326/latest.log)
Here's the crash report and latest log, maybe it could help

**Comment by Faboslav** [comment]
I am sorry, there is just no work around this thing, still the same error message `Failure message: Mod friendsandfoes requires forge 43.1.0 or above`, i believe you need to either update forge and remove certain mods, or remove just friends&foes mod and you will be fine.

**Comment by randomguy132** [comment]
ok then
