### ISSUE TITLE
Tuff golem can't be spawned on arclight server

### ISSUE THREAD

**Issue by Miaochan** [Faboslav/friends-and-foes#104]
### Minecraft version information

1.19.2

### Mod loader information

Forge

### Mod loader version information

43.2.0

### Mod version information

friendsandfoes-forge-mc1.19.2-1.8.1.jar

### Expected Behavior

Tuff golem should be spawned

### Actual Behavior

error message displayed

### Reproduction Steps

1.Start [Arclight](https://github.com/IzzelAliz/Arclight) server
2.Spawn tuff golem using tuff golem spawner
[latest.log](https://github.com/Faboslav/friends-and-foes/files/11225003/latest.log)

### Screenshots & files

none.

**Comment by Faboslav** [comment]
Can this be reproduced using normal(read official) server jar? If so then i will try to fix this, otherwise i would recommend to report this issue to the Arclight github.

**Comment by Miaochan** [comment]
> Can this be reproduced using normal(read official) server jar? If so then i will try to fix this, otherwise i would recommend to report this issue to the Arclight github.

Nope.I'm glad to report this issue to them but 1.19.2 is not their supported version right now,so they will not fix it for 1.19.2.It will be regretful.
