### ISSUE TITLE
Server crashes while stronghold generated

### ISSUE THREAD

**Issue by Miaochan** [Faboslav/friends-and-foes#105]
### Minecraft version information

1.19.2

### Mod loader information

Forge

### Mod loader version information

43.2.0

### Mod version information

friendsandfoes-forge-mc1.19.2-1.8.1.jar

### Reproduction Steps

1.Start [Arclight](https://github.com/IzzelAliz/Arclight) server
2.Teleport to a stonghold which have not been generated
3.Server crashes

### Crash Report and latest.log

[latest.log](https://github.com/Faboslav/friends-and-foes/files/11225119/latest.log)

**Comment by Miaochan** [comment]
> Can this be reproduced using normal(read official) server jar? If so then i will try to fix this, otherwise i would recommend to report this issue to the Arclight github.

Nope.I'm glad to report this issue to them but 1.19.2 is not their supported version right now,so they will not fix it for 1.19.2.It will be regretful.

**Comment by Miaochan** [comment]
This problem don't exist on 1.6.8 vesion.The problem appears before I updated it to the latest version.

**Comment by Faboslav** [comment]
I mean even if i want, based on that crash log, i cant fix anything i think, or at least i dont know what.

**Comment by Miaochan** [comment]
> I mean even if i want, based on that crash log, i cant fix anything i think, or at least i dont know what.

Okay,I will report to them.Thank you for your reply!

**Comment by Faboslav** [comment]
No problem :).
