### ISSUE TITLE
Missing Features (Entities)

### ISSUE THREAD

**Issue by Relaxing9** [Faboslav/friends-and-foes#107]
### Minecraft version information

Magma version 1.18.2-62ec6408 (Implementing API version 1.18.2-R0.1-SNAPSHOT, Forge Version 40.2.1)

### Mod loader information

Forge

### Mod loader version information

40.2.1 (Forge)

### Mod version information

1.4.7

### Expected Behavior

Feature should be realized and that way shouldn't error on my console.

### Actual Behavior

Seems to be missing entity types

### Reproduction Steps

1. Load mod into Magma using my config
2. Observe

### Screenshots & files

Friends&Foes Config: https://paste.gg/p/anonymous/a3c7537f56654d51a69db5afe257f77f
Logs: https://mclo.gs/1pvaLrm
![image](https://user-images.githubusercontent.com/41935047/235331765-22f8db13-b858-42fd-ac74-da16ccfb6127.png)

**Comment by Faboslav** [comment]
Hello, i think this is probably a magma or architectury fault, but as the mod was pretty stable back in the time of 1.18.2 and architectury without any of mentioned warnings, i bet on the magma side.

**Comment by Faboslav** [comment]
I see that you created issue on the architectury side, thus closing this issue now, hopefully they will get this fixed, or at least provide some explanation.
