### ISSUE TITLE
Slim skin totem of illusion

### ISSUE THREAD

**Issue by Arrocha08** [Faboslav/friends-and-foes#109]
### Minecraft version information

1.19.4

### Mod loader information

Fabric

### Mod loader version information

(Fabric) 0.80.0

### Mod version information

1.8.2

### Expected Behavior

My skin should appear with slim version and second layer skin as well

### Actual Behavior

My skin showed as original size version

### Reproduction Steps

just using totem of illusion

### Screenshots & files

![Untitled](https://github.com/Faboslav/friends-and-foes/assets/105840060/b2bc4096-7d62-4b6c-9d2b-d896ab592a6a)

**Comment by Faboslav** [comment]
@Arrocha08 It need some testing, but i think i found the solution to this problem, so with next release, slim skins should be supported.

**Comment by Arrocha08** [comment]
Wanderful!

**Comment by Arrocha08** [comment]
Wonderful!

**Comment by Faboslav** [comment]
Should be fixed with new release https://www.curseforge.com/minecraft/mc-mods/friends-and-foes/files.
