### ISSUE TITLE
Github Wiki Missing Words?

### ISSUE THREAD

**Issue by milkev** [Faboslav/friends-and-foes#11]
### Minecraft version information

na

### Mod version information

na

### Expected Behavior

Word is present. Probably exp?

### Actual Behavior

No word is present.

### Reproduction Steps

visit [this](https://github.com/Faboslav/friends-and-foes/wiki/Moobloom#drops) wiki page, and scroll down to the loot section

### Screenshots & files

![image](https://user-images.githubusercontent.com/22010128/149032805-568a30c7-1c37-4476-9767-4034f0a7c144.png)

**Comment by Faboslav** [comment]
Thank you for the issue, i will fix this along with few other missing words/pages.

**Comment by Faboslav** [comment]
I am sorry, that this is taking too long, hopefully i will take care of the wiki this week :).

**Comment by Faboslav** [comment]
I fixed that one.
