### ISSUE TITLE
[TRANSLATION] Suggestion for a very slight change in one single line of the Italian translation

### ISSUE THREAD

**Issue by 71CXE03** [Faboslav/friends-and-foes#110]
Hello! 

Playing on latest version: 1.8.2 for Minecraft 1.19.4

Would like to suggest a change in the translation from English into Italian for a single sentence found in the "Advancements" tab.

Sentence in question is: "Off you go" translated into "Vai via".
I'm awful at explaining grammar or using technical language terms but my suggestion would be to change it from "Vai via" to "Eccolo che va!". It's the best match I could come up with and it's not easy haha but this way it feels more like "Off he goes, doing his thing" instead of "Go away"

Cheers!!

**Comment by Faboslav** [comment]
Hello, I will change the translation with next release, thanks! :)

**Comment by 71CXE03** [comment]
No problem! Take your time! Mine's more a suggestion to be taken with the Italian translator if you want to double-verify

Cheers!!
