### ISSUE TITLE
Totem Of Illusion Causing Crashes

### ISSUE THREAD

**Issue by MoonstruckSpirit** [Faboslav/friends-and-foes#111]
### Minecraft version information

1.19,2

### Mod loader information

Forge

### Mod loader version information

43.2.11

### Mod version information

 friendsandfoes-forge-mc1.19.2-1.8.2.jar

### Expected Behavior

Expected Behaviour: No Crashes

### Actual Behavior

It crashes the server, I can't tell you how exactly. I think it's when I die with the totem but it's whenever I have the totems

### Reproduction Steps

Not too sure but at least have the totem and try to get killed by an entity

### Screenshots & files

I crashed on two seperate occasions. So here are the relevant files.

[crash-2023-05-22_14.01.40-server(2).txt](https://github.com/Faboslav/friends-and-foes/files/11535942/crash-2023-05-22_14.01.40-server.2.txt)
[crash-2023-05-19_14.33.34-server(2).txt](https://github.com/Faboslav/friends-and-foes/files/11535944/crash-2023-05-19_14.33.34-server.2.txt)

**Comment by Faboslav** [comment]
I look into it, but could not find anything yet, my guess is, could you try this on separate mc instance only with mentioned forge and friends&foes mod please?

**Comment by MoonstruckSpirit** [comment]
Hey! Sorry, I will have to test this when I have time but I stronly believe this is a Canary issue for the moment

**Comment by Faboslav** [comment]
Yeah, that is one of the possibilities i thought based on the logs. Let me know, if there is any new context

**Comment by Faboslav** [comment]
Will close this for now, if wanted reopen the issue please.
