### ISSUE TITLE
A way to turn off itens/blocks

### ISSUE THREAD

**Issue by Arrocha08** [Faboslav/friends-and-foes#112]
Pls, a way to turn off the:
-Beehives woodtype
-Oxidized Lightning Rods
-Copper bottoms
-Wildfire crown, etc

The others we can just not craft, but the beehives we need to farm oak planks.

**Comment by Faboslav** [comment]
Hello, there is a separate mod just for this, i just dont know the name right now, but you can disable certain crafting recipes with it. Also complexity behind disabling items and related stuff is not worth doing it. I will think about this when all major features of the mod are already in place, which is not a current state.

**Comment by Arrocha08** [comment]
Got it. I'll try to find the mod, Thank you

**Comment by Arrocha08** [comment]
I found it:
CraftTweaker: https://www.curseforge.com/minecraft/mc-mods/crafttweaker
