### ISSUE TITLE
Tuff Golem AI Glitch

### ISSUE THREAD

**Issue by JosephLeanos** [Faboslav/friends-and-foes#113]
### Minecraft version information

1.19.4

### Mod loader information

Forge

### Mod loader version information

(Forge) 45.0.66

### Mod version information

1.8.2

### Expected Behavior

The Tuff Golem is supposed to return to its original place after a while and go to sleep, no matter its surrounding.

### Actual Behavior

When inside an enclosed area, the Tuff Golem will end up not returning to its original place, though it will go somewhere close, and it will remain there without going to sleep, and trying to move it will just make it walk right back to that area.

### Reproduction Steps

1. Spawn Tuff Golem (Either with Spawn Egg or by creating it manually) in an enclosed area. (My experience was in a 7x7 area with 5 block high walls surrounding it. Roof is not required.)
2. Wait for a while.
3. Watch the Tuff Golem move to an area it was not created in without moving.
4. Try to move it to confirm if it's stuck or not. (This may take a few minutes.)

**Comment by Faboslav** [comment]
Hello there, would it be possible to get the video recording of this behaviour?

**Comment by JosephLeanos** [comment]
https://github.com/Faboslav/friends-and-foes/assets/135401069/e4e50fff-6387-41a6-9b88-0e177c6a7202

I apologize for the low quality. I had to lower the file size a lot.

**Comment by Faboslav** [comment]
Will release 1.20 first as a priority and then check this later, sorry for the delay, also thank you very much for the video!

**Comment by Faboslav** [comment]
This should be resolved with newest version of the mod, can you please try and let me know?
