### ISSUE TITLE
Mauler Infinite XP Glitch

### ISSUE THREAD

**Issue by spookwoah** [Faboslav/friends-and-foes#116]
### Minecraft version information

Minecraft 1.20

### Mod loader information

Fabric

### Mod loader version information

fabric-loader-0.14.21-1.20

### Mod version information

1.20

### Expected Behavior

Mauler eats enchanted item and gives back a proportional amount of experience thru experience bottles, regardless of what hand you feed them with.

### Actual Behavior

Mauler provides seemingly infinite experience bottles.

### Reproduction Steps

1. Find Mauler naturally or spawn in using egg.
2. Put enchanted item in offhand.
3. Feed enchanted item to mauler.
4. Continue to right click mauler as if you were feeding it, regardless of the fact there is nothing being fed.
5. Bottle experience from mauler.
6. Repeat steps 4 and five infinitely.

### Screenshots & files

https://github.com/Faboslav/friends-and-foes/assets/83798319/ac380636-6421-460c-9f62-4aaa95b8e3dc

**Comment by Faboslav** [comment]
Thank you for very detailed report, i was able to reproduce it and found the problem, will be fixed with the next release.

**Comment by Faboslav** [comment]
This should be resolved with newest version of the mod, can you please try and let me know?

**Comment by spookwoah** [comment]
> This should be resolved with newest version of the mod, can you please try and let me know?

Would that be the newest version on Curseforge or the updated code from here on Github? If it's the code here, how exactly would I install that to test? We are running the most recent release from Curseforge found here (https://www.curseforge.com/minecraft/mc-mods/friends-and-foes/files?version=1.20.1) unless that has been updated since the stated June 8th release.
