### ISSUE TITLE
Incomplete Set of Tags for Copper Buttons

### ISSUE THREAD

**Issue by sorat0mo** [Faboslav/friends-and-foes#12]
### Minecraft version information

1.18.1

### Mod version information

1.1.2

### Expected Behavior

Able to connect to multiplayer and play

### Actual Behavior

An error "Incomplete set of Tags received from servers" occured. Upon examining the log, I found the following lines:

`[20:26:03] [Render thread/WARN]: Incomplete server tags, disconnecting. Missing: {ResourceKey[minecraft:root / minecraft:block]=[friendsandfoes:copper_buttons]}`

### Reproduction Steps

Just install the mod and try joining a multiplayer session.

### Screenshots & files

[latest.log](https://github.com/Faboslav/friends-and-foes/files/7854580/latest.log)

**Comment by Faboslav** [comment]
Thank you for issue, i will correct the copper button tags. Fix will be probably part of the `1.2.0` release hopefully this week along with the Illusioner.

**Comment by sorat0mo** [comment]
> Thank you for taking time to create the issue. I will correct the copper button tags. Fix will be probably part of the `1.2.0` release hopefully this week along with the Illusioner.

I appreciated the swift reply. I noticed it was probably caused by server side not having the mod while client side does. When I install the mod on both sides, no such error occured.

**Comment by Faboslav** [comment]
Oh that is great news :D, anyway i found another issue related to the copper button tags, so at least i fixed that.

**Comment by Faboslav** [comment]
If you have any other question/feature request/issues you are more than welcome to join the discord server(https://discord.com/invite/bFYFvu3v) and discuss it there :).
