### ISSUE TITLE
Acacia Beehive disappears when broken with Silk Touch axe

### ISSUE THREAD

**Issue by rowanrooks** [Faboslav/friends-and-foes#120]
### Minecraft version information

1.19.2

### Mod loader information

Forge

### Mod loader version information

43.2.8 (Forge)

### Mod version information

1.8.2

### Expected Behavior

When I break the Acacia Beehive block with an axe that has the Silk Touch enchantment, I expect that I will receive the Acacia Beehive item.

### Actual Behavior

When I break the Acacia Beehive block with an axe that has the Silk Touch enchantment, the Acacia Beehive is destroyed and it does not drop itself. Additionally, the bees and honey within the hive are destroyed. (This issue does not occur with other Beehive variants from this mod.)

### Reproduction Steps

1. Place Acacia Beehive block.
2. Use a Silk Touch axe to break the Acacia Beehive.
3. Acacia Beehive is not dropped as an item in the world or present in the player's inventory.

**Comment by Faboslav** [comment]
Hello there, i found the problem, will fix be with the next release.
