### ISSUE TITLE
Server crash possibly caused by friends and foes(?)

### ISSUE THREAD

**Issue by TenKotowsky** [Faboslav/friends-and-foes#123]
### Minecraft version information

1.20.1

### Mod loader information

Fabric

### Mod loader version information

0.14.21

### Mod version information

1.9.2

### Reproduction Steps

The bug occurs randomly out of nowhere. I could be standing still and not doing anything and the game crashes by itself

### Crash Report and latest.log

The crash report didn't generate now, but before I installed Unsafe World Random Access Detector to see what could be causing the issue I got this crash report:
https://gist.github.com/TenKotowsky/b237cd03176da8f5494932a1b90c0a74

latest.log:
https://gist.github.com/TenKotowsky/985d6310e08adadf26fb28b3626f104b

**Comment by Faboslav** [comment]
Do you use any mod, which would try to multi-thread things?

**Comment by TenKotowsky** [comment]
I use f&f together with many other mods, but I don't really know if they are trying to do stuff multi-thread.
Thought one mod that I suspect of doing so is Async Locator, but I'm not sure if its the mod that could cause the issue

**Comment by Faboslav** [comment]
Please do re-open the issue, if you have anything new related to this.
