### ISSUE TITLE
Fight with Blaze Boss crash

### ISSUE THREAD

**Issue by AbsorbingSafe11** [Faboslav/friends-and-foes#124]
### Minecraft version information

1.20.01

### Mod loader information

Forge

### Mod loader version information

Forge 47.1.0

### Mod version information

friendsandfoes-forge-mc1.20.1-1.9.2.jar

### Reproduction Steps

1) fight Blaze boss like any other mob (close combat with a sword)
2) right as all the shields look like they will be gone the game crashes (all armor breaks as well)

### Crash Report and latest.log

[crash-2023-07-08_17.00.18-server.txt](https://github.com/Faboslav/friends-and-foes/files/11992415/crash-2023-07-08_17.00.18-server.txt)
[latest.log](https://github.com/Faboslav/friends-and-foes/files/11992416/latest.log)

### Additional information

Playing the modpack TNP Limitless 7 - LL7 and the file version is Limitless 7 - v0.7.1
(sorry if enough info wasn't provided, as I don't use Github a lot)

**Comment by AbsorbingSafe11** [comment]
I think its name is the WildFire, not Blaze boss, but Blaze boss was all I could think of when I first made the issue

**Comment by Faboslav** [comment]
I think that I found possible issue(we will see), will try to fix it asap. Thank you for the report :).
