### ISSUE TITLE
conflict with Better F3 mod

### ISSUE THREAD

**Issue by 0SNIFF** [Faboslav/friends-and-foes#128]
### Minecraft version information

1.19.2

### Mod loader information

Forge

### Mod loader version information

forge 1.18.2-40.2.4

### Mod version information

friendsandfoes-forge-mc1.20.1-1.9.3.jar

### Expected Behavior

expected good compatibility of friends and foes mod

### Actual Behavior

Mod conflicts with Better F3 mod.
(https://github.com/Faboslav/friends-and-foes/assets/86169273/65bb2830-4434-4730-b3a0-915f5cb71dd3)

### Reproduction Steps

just install these two mods

**Comment by Faboslav** [comment]
This is on the BetterF3 side https://github.com/cominixo/BetterF3/issues/84, or even if this this not a cause of this issue, it has to be probably fixed on their side, can you create an issue there please?

**Comment by Faboslav** [comment]
Also your provided versions are very inconsistent, you mention 1.19.2 with forge for 1.18.2 and friends&foes for 1.20.1
