### ISSUE TITLE
Sugar cane crashes the game because of this mod?

### ISSUE THREAD

**Issue by NewAgeSoldier** [Faboslav/friends-and-foes#130]
### Minecraft version information

1.20.1 

### Mod loader information

Forge

### Mod loader version information

Forge 47.1.26 (can't update further because of other mods)

### Mod version information

1.9.3

### Reproduction Steps

![image](https://github.com/Faboslav/friends-and-foes/assets/10442785/c14694bb-8897-4b7e-b45e-809e0adf15a3)

Breaking sugar cane

### Crash Report and latest.log

[latest.log](https://github.com/Faboslav/friends-and-foes/files/12136797/latest.log)

### Additional information

I have more questions than answers?

**Comment by Faboslav** [comment]
Hello, based on provided log, this is not related to this mod in any way.
