### ISSUE TITLE
Player model not working

### ISSUE THREAD

**Issue by SebSemos** [Faboslav/friends-and-foes#136]
### Minecraft version information

1.20.1

### Mod loader information

Fabric

### Mod loader version information

fabric-api-0.86.1+1.20.1

### Mod version information

friendsandfoes-fabric-mc1.20.1-1.9.4

### Expected Behavior

Using a ressource pack that give animation to the player (like Fresh animation on mobs) doesn't work with Friend and Foes installed.
Such animation possible with Entity Model Feature.

Player should display like this, and move around smootlhly etc...:
![2023-08-31_01 43 13](https://github.com/Faboslav/friends-and-foes/assets/89230340/425147c7-abc2-4f4e-9169-c9c224539200)

### Actual Behavior

But it does it vanilla style still

![2023-08-31_01 41 26](https://github.com/Faboslav/friends-and-foes/assets/89230340/0f028230-4ed2-442d-a3a3-9755969e04ca)

### Reproduction Steps

Ressource pack I use from Jonny Bro

[Fresh-Player-Models.zip](https://github.com/Faboslav/friends-and-foes/files/12480887/Fresh-Player-Models.zip)

**Comment by Faboslav** [comment]
I tested it and can confirm that it does not work, which is weird, because friends&foes does not edit player rendering or anything related to the player in any way.

**Comment by JonnyBro** [comment]
Maybe that's an conflict between this mod and [EMF](https://github.com/Traben-0/Entity_Model_Features)?

**Comment by SebSemos** [comment]
Good news!! Traben did rewrite EMF for newest version, and issue is gone with it! :)

**Comment by Faboslav** [comment]
Happy to hear this, at last one issue i dont have to resolve :D.
