### ISSUE TITLE
Startup crash on Quilt 1.20.1 due to Mixin Failure

### ISSUE THREAD

**Issue by lxly9** [Faboslav/friends-and-foes#138]
### Minecraft version information

1.20.1

### Mod loader information

Quilt

### Mod loader version information

7.2.2+0.88.1-1.20.1

### Mod version information

1.9.3

### Reproduction Steps

> Install Friends&Foes Quilt with the other mods mentioned in the log
> crash on startup

### Crash Report and latest.log

[crash-2023-09-13_19.01.46.8566-quilt_loader.txt](https://github.com/Faboslav/friends-and-foes/files/12600216/crash-2023-09-13_19.01.46.8566-quilt_loader.txt)
[latest.log](https://github.com/Faboslav/friends-and-foes/files/12600220/latest.log)

**Comment by Faboslav** [comment]
Hello there, quilt is no longer directly supported, due to these kind of random errors/crashes, please use fabric version of the mod.
