### ISSUE TITLE
Mauler causes everyone nearby to constantly crash.

### ISSUE THREAD

**Issue by erikduss** [Faboslav/friends-and-foes#139]
### Minecraft version information

1.20,1

### Mod loader information

Fabric

### Mod loader version information

Fabric - 0.14.22

### Mod version information

friendsandfoes-fabric-mc1.20.1-1.9.4

### Reproduction Steps

1. Spawn Mauler.
2. Cause Mauler to burrow.
3. Everyone nearby crashes.
4. Reconnect & crash again (seems to be linked to a specific person, only when my friend (who interacted with the mauler) logs in it crashes everyone nearby).

### Crash Report and latest.log

[crash-2023-09-14_23.52.48-client.txt](https://github.com/Faboslav/friends-and-foes/files/12614170/crash-2023-09-14_23.52.48-client.txt)

(Below is the log of when it happened)
[2023-09-14-1.log](https://github.com/Faboslav/friends-and-foes/files/12614190/2023-09-14-1.log)

(Server Log)
[2023-09-14-2.log](https://github.com/Faboslav/friends-and-foes/files/12614199/2023-09-14-2.log)

### Additional information

- Killing all maulers does not resolve the issue.
- If far enough away from where mauler burrows, wont crash.
- Disabling maulers in config does not work.
- If player that causes the crashes dies, it does not resolve the issue.
- The crash is immediately, can't see any actual mauler nearby.
- F3 + B does not show any mauler in the area.
- Removing blocks where mauler could possibly be burrowed does not resolve the issue.

Modpack used: Prominence II [FABRIC]

**Comment by Faboslav** [comment]
Hello there, i checked the code and probably found an issue, will try to release fix sometime today or tomorrow.

**Comment by erikduss** [comment]
> Hello there, i checked the code and probably found an issue, will try to release fix sometime today or tomorrow.

Awesome, thanks for the quick reply! (and hopefully fix)

**Comment by Faboslav** [comment]
This should be resolved with https://legacy.curseforge.com/minecraft/mc-mods/friends-and-foes/files/4754915.
