### ISSUE TITLE
add zh_cn lang for 1.2.0

### ISSUE THREAD

**Issue by chen-Futuro** [Faboslav/friends-and-foes#14]
{
  "advancements.husbandry.beehive.title": "守护者",
  "advancements.husbandry.beehive.description": "获得任意类型的蜂箱",
  "advancements.adventure.kill_illusioner.title": "幻术世界",
  "advancements.adventure.kill_illusioner.description": "杀死幻术师真身",
  "advancements.husbandry.shear_a_moobloom.title": "哞哞！",
  "advancements.husbandry.shear_a_moobloom.description": "在哞花身上剪下花朵",
  "advancements.adventure.summon_copper_golem.title": "走起来了",
  "advancements.adventure.summon_copper_golem.description": "召唤一个铜傀儡",
  "advancements.husbandry.tame_a_glare.title": "脾气暴躁又可爱",
  "advancements.husbandry.tame_a_glare.description": "驯服眩光",
  "block.friendsandfoes.buttercup": "绒花",
  "block.minecraft.beehive": "橡木蜂巢",
  "block.friendsandfoes.acacia_beehive": "金合欢木蜂巢",
  "block.friendsandfoes.birch_beehive": "桦木蜂巢",
  "block.friendsandfoes.crimson_beehive": "绯红木蜂巢",
  "block.friendsandfoes.dark_oak_beehive": "深色橡木蜂巢",
  "block.friendsandfoes.jungle_beehive": "丛林木蜂巢",
  "block.friendsandfoes.spruce_beehive": "云杉木蜂巢",
  "block.friendsandfoes.warped_beehive": "诡异木蜂巢",
  "block.friendsandfoes.copper_button": "铜按钮",
  "block.friendsandfoes.exposed_copper_button": "裸露的铜按钮",
  "block.friendsandfoes.weathered_copper_button": "风化的铜按钮",
  "block.friendsandfoes.oxidized_copper_button": "氧化的铜按钮",
  "block.friendsandfoes.waxed_copper_button": "涂蜡的铜按钮",
  "block.friendsandfoes.waxed_exposed_copper_button": "涂蜡的裸露铜按钮",
  "block.friendsandfoes.waxed_weathered_copper_button": "涂蜡的风化铜按钮",
  "block.friendsandfoes.waxed_oxidized_copper_button": "涂蜡的氧化铜按钮",
  "entity.minecraft.villager.beekeeper": "养蜂人",
  "entity.friendsandfoes.copper_golem": "铜傀儡",
  "entity.friendsandfoes.glare": "眩光",
  "entity.friendsandfoes.moobloom": "哞花",
  "item.friendsandfoes.buttercup": "绒花",
  "item.friendsandfoes.glare_spawn_egg": "眩光刷怪蛋",
  "item.friendsandfoes.copper_golem_spawn_egg": "铜傀儡刷怪蛋",
  "item.friendsandfoes.illusioner_spawn_egg": "幻术师刷怪蛋",
  "item.friendsandfoes.moobloom_spawn_egg": "哞花刷怪蛋",
  "subtitle.entity.friendsandfoes.glare.ambient": "眩光：游荡",
  "subtitle.entity.friendsandfoes.glare.death": "眩光：死亡",
  "subtitle.entity.friendsandfoes.glare.eat": "眩光：进食",
  "subtitle.entity.friendsandfoes.glare.hurt": "眩光：受伤",
  "subtitle.entity.friendsandfoes.copper_golem.death": "铜傀儡：死亡",
  "subtitle.entity.friendsandfoes.copper_golem.head_spin": "铜傀儡：旋转头部",
  "subtitle.entity.friendsandfoes.copper_golem.hurt": "铜傀儡：受伤",
  "subtitle.entity.friendsandfoes.copper_golem.repair": "铜傀儡：修复",
  "subtitle.entity.friendsandfoes.copper_golem.step": "铜傀儡：脚步声"
}

**Comment by chen-Futuro** [comment]
Updated several entries that fixed minor issues

  "block.friendsandfoes.exposed_copper_button": "斑驳的铜按钮",
  "block.friendsandfoes.weathered_copper_button": "锈蚀的铜按钮",
  "block.friendsandfoes.oxidized_copper_button": "氧化的铜按钮",
  "block.friendsandfoes.waxed_exposed_copper_button": "斑驳的涂蜡铜按钮",
  "block.friendsandfoes.waxed_weathered_copper_button": "锈蚀的涂蜡铜按钮",
  "block.friendsandfoes.waxed_oxidized_copper_button": "氧化的涂蜡铜按钮",

**Comment by Faboslav** [comment]
Thank you for the update! I will release `1.2.1` probably version in a few hours with your translations, in the meantime you are welcome to join the discord server https://discord.com/invite/sEdM6KRNdZ as i will announce the release there :).
