### ISSUE TITLE
Mobs like Copper Golem, Tuff Golem or Illusioner are immune to things like being blast resistant to beds and not TNT and immune to things like fall damage and fire or lava

### ISSUE THREAD

**Issue by PlanetGalaxy2008** [Faboslav/friends-and-foes#141]
### Minecraft version information

1.20.1

### Mod loader information

Fabric

### Mod loader version information

0.14.22

### Mod version information

1.9.6

### Expected Behavior

Hi, idk if this issue is only on Fabric or if someone reported this glitch before but there is a glitch that makes mobs like Copper Golem, Tuff Golem and Illusioner to be blast resistant to beds and not tnt and immune to things like fall damage and fire when these mobs probably shouldn't be able to do this

### Actual Behavior

One day, I wanted to see if the Illusioner can die to things like beds or respawn anchors because it was immune on fire while it can blind you on hard, I summoned the Illusioner and placed the bed, pressed the right click on bed and the illusioner survived without taking any damage but it dies to tnt or a creeper, when I saw that it didn't die to a bed but died to tnt, I wanted to see if it can die to fall damage, and that also failed by not taking any damage from falling

### Reproduction Steps

Example of what is happening with these mobs:
1. I place the bed or respawn anchor
2. I summon the copper golem, tuff golem or Illusioner
3. I press on the bed and it explodes
4. Nothing happens to them
5. I place a block at a very high position
6. I summon the copper golem, tuff golem or Illusioner
7. I break the block
8. Survive the fall without taking any damage

Some mobs like the Glare or Iceologer are fine but mobs like Copper Golem or Tuff Golem aren't

### Screenshots & files

![ezgif com-video-to-gif](https://github.com/Faboslav/friends-and-foes/assets/106810679/f318a00c-a565-4360-8bc3-93570722bb37)
![ezgif com-video-to-gif (1)](https://github.com/Faboslav/friends-and-foes/assets/106810679/217473bc-6848-4d89-8dac-8b56e757da7e)

**Comment by Faboslav** [comment]
All golems should be immune to fall damage and certain other damage sources, but lava or explosions should probably kill them, i will try to do some testing later.

**Comment by PlanetGalaxy2008** [comment]
Thanks

**Comment by qznfbnj** [comment]
I'm playing with friendsandfoes-forge-mc1.19.2-1.8.8, why does the kill command not work on them?

**Comment by PlanetGalaxy2008** [comment]
Bro same, I almost forgot that if you type something like /kill
@e[type=friends and foes:copper_golem], it will kill all mobs on the map
except the copper golem, the kill command on Illusioner also has the issue
but at least it doesn't kill everything on the map

**Comment by Faboslav** [comment]
This will be fixed in the next release :).

**Comment by PlanetGalaxy2008** [comment]
Awesome, thanks!

**Comment by Faboslav** [comment]
You can download new release, should be fixed with it.

**Comment by PlanetGalaxy2008** [comment]
Everything should be working by now
