### ISSUE TITLE
rascal

### ISSUE THREAD

**Issue by Meow-purr** [Faboslav/friends-and-foes#142]
im pretty sure you know what it is

**Comment by Faboslav** [comment]
Its WIP, its coming, also this is a very bad issue.

**Comment by Meow-purr** [comment]
is it on a git branch?

**Comment by Faboslav** [comment]
Yeah, `rascal`, i would not recommend running it, just wait for the release.

**Comment by Meow-purr** [comment]
it semms to be aded in #149 but only to 1.19.4 is it added or not?(take your time as modding takes time and game balencing takes time)

**Comment by Faboslav** [comment]
You can join the discord server if you want, rascal is already released for 1.19.x and 1.20.x.
