### ISSUE TITLE
[Feature Request] Mobs From Biome Votes

### ISSUE THREAD

**Issue by Shadownite64** [Faboslav/friends-and-foes#144]
Minecon 2018 & 2019, there were biome votes instead of mob votes, there were biome votes, and while these biomes would get updated eventually, its been 4 years since the last one, and only the swamp was updated, there were several mobs from these votes that I think should be added. I also think the mobs from the Chinese mob vote should be added as well, these additions would fully round out this mod and make it the definitive one to add these creatures.

These creatures include
- Baiji Dolphin
- Chinese Alligator
- Snub-Nosed Monkey
- Meerkat
- Ostrich
- Termite
- Vulture
- White Lipped Deer

**Comment by Faboslav** [comment]
There is already multiple mods implementing the biome votes, i am currently not interested in that one, also chinese mob vote is out of question for now.
