### ISSUE TITLE
Illusioner is undefeatable using female villagers

### ISSUE THREAD

**Issue by Arathorne** [Faboslav/friends-and-foes#145]
### Minecraft version information

1.19.2

### Mod loader information

Forge

### Mod loader version information

43.2.3

### Mod version information

1.8.8

### Expected Behavior

illusioner illusions disappears after death

### Actual Behavior

the illusion doesn't die and respawn another 8 illusions

### Reproduction Steps

get illusioner with female villagers mod installed

**Comment by Arathorne** [comment]
![obraz](https://github.com/Faboslav/friends-and-foes/assets/60345302/a863e094-cfd7-45f7-a893-7268437ff043)
![obraz](https://github.com/Faboslav/friends-and-foes/assets/60345302/aaa64d40-4096-4f66-a3e1-61ba21dbbac5)
![obraz](https://github.com/Faboslav/friends-and-foes/assets/60345302/02cdb266-a622-439f-8570-b94e06475c59)
Those screens represent the issue, also the thing that you cannot kill those entities with kill command either

**Comment by Arathorne** [comment]
yeah it is not persistent without female villagers
basiclly when the friends and foes illusioner got hit he spawn illusions, but when having female villagers, they dont despawn when the first illusioner is killed
and that applies to evry illusioner
and thats why they are duping

**Comment by Faboslav** [comment]
This needs to be fixed on female villagers end, basically it should change all Overrides to some kind of mixins.

**Comment by Faboslav** [comment]
I opened this https://github.com/Daripher/Female-Villagers/issues/16 with "instructions" how to resolve this, closing on my side, nothing i can do here.
