### ISSUE TITLE
If a item from this mod gets added to MineCraft will you convert the items two the new one or kepp them only in this mod

### ISSUE THREAD

**Issue by Meow-purr** [Faboslav/friends-and-foes#151]
Im asking due tow copper theme of the trial chambers (coming in 1.21)

**Comment by Faboslav** [comment]
If you mean items like copper buttons, then yes, i will keep the original ones and remove buttons from this mod.

**Comment by Daralexen05** [comment]
> Im asking due tow copper theme of the trial chambers (coming in 1.21)

Sadly, Copper and Tuff Golem are currently not being considered for 1.21. Maybe Mojang will add them as a surprise closer to the release.

**Comment by Velocifyer** [comment]
This is Super Relevant right now
