### ISSUE TITLE
Copper Golems and Tuff Golems are now taking fall damage even tho you said before that both golems should be immune to fall damage

### ISSUE THREAD

**Issue by PlanetGalaxy2008** [Faboslav/friends-and-foes#153]
Alright so I was last night checking if mobs like Copper Golem and Illusioner were finally fixed and the bug fix worked but the problem happened when Copper Golems and Tuff Golems take fall damage, but this is not the only issue, there is only one more mob remaining to fix and that mob is the Wildfire because I forgot that this mob even existed...

I couldn't send before because it was a thunderstorm in my area and my wifi went out

So everything is working fine for Copper Golem, Tuff Golem and Illusioner but Golems are now somehow taking fall damage and Wildlife is remaining to be fixed 

(My Minecraft is kinda laggy, sry)

![ezgif com-video-to-gif (2)](https://github.com/Faboslav/friends-and-foes/assets/106810679/4772e3c9-00de-430c-96d3-25164c2dca4d)

**Comment by Faboslav** [comment]
Yeah, i forgot too, will be also fixed with next release, thanks for testing and reporting! :).

**Comment by qznfbnj** [comment]
I can't use /kill command to kill wildfire, whether they have shields or not.
friendsandfoes-forge-mc1.19.2-1.8.10

**Comment by Faboslav** [comment]
Fixed with the new release.
