### ISSUE TITLE
Insufficient maximum stack size (error in server log)

### ISSUE THREAD

**Issue by DrLeonardo95** [Faboslav/friends-and-foes#156]
### Minecraft version information

1.20.1

### Mod loader information

Fabric

### Mod loader version information

Fabric Loader 0.14.22

### Mod version information

1.9.8

### Expected Behavior

There is an error in the server logs, but it is not recorded in the letest.log of the server.

### Actual Behavior

Effect on game unknown

### Reproduction Steps

There may be a conflict with some mod, but we don’t know which one.

### Screenshots & files

[error_mod.txt](https://github.com/Faboslav/friends-and-foes/files/13210103/error_mod.txt)
[latest.log](https://github.com/Faboslav/friends-and-foes/files/13210104/latest.log) (server logs [empty] for my modlist)

**Comment by Faboslav** [comment]
This has nothing to do with friendsandfoes, you just connected one warning from the mod with another non-related error.
