### ISSUE TITLE
1.20.1 1.9.6+ crashes due to incompatibility

### ISSUE THREAD

**Issue by snoandpetals** [Faboslav/friends-and-foes#157]
### Minecraft version information

1.20.1

### Mod loader information

Fabric

### Mod loader version information

0.14.22

### Mod version information

1.9.6+

### Reproduction Steps

Try to launch game

### Crash Report and latest.log

https://mclo.gs/9ncCkBE

**Comment by Faboslav** [comment]
There is nothing in the logs related to friends&foes, what do you mean by incompatibility?

**Comment by snoandpetals** [comment]
When I swap out F&F 1.9.5 for 1.9.6 and above, I crash. I don't know why it doesn't mention it in the logs, I'm assuming something about the update upsets sodium. I'll try disabling different mods and seeing if a specific one lets F&F 1.9.6 work properly

**Comment by Faboslav** [comment]
Can you please try to also update all the mods, so for example friends&foes to 1.9.8? I use that with Sodium 0.5.3 without any problems

**Comment by snoandpetals** [comment]
MemoryLeakFix v1.1.1 was the incompatibility. Updating to 1.1.2 fixes compatibility with F&F 1.9.6+, sorry for the inconvenience. Thanks for all your hard work 💚

**Comment by Faboslav** [comment]
No problem, happy that it works :).
