### ISSUE TITLE
[1.19.2] Incomplete es_es translations

### ISSUE THREAD

**Issue by Daralexen05** [Faboslav/friends-and-foes#159]
I updated the mod to 1.19.2, but the Spanish (Spain) translations are incomplete. Were they never finished or is there something wrong with the .json file?

**Comment by Faboslav** [comment]
Hello, translations are currently pretty random, if someone makes PR, i merge it, that's basically all.

**Comment by Daralexen05** [comment]
> Hello, translations are currently pretty random, if someone makes PR, i merge it, that's basically all.

Is it possible for me to add to the PR or edit the es_es json file to add in the incomplete translations?

**Comment by Faboslav** [comment]
If you can fork the repo and create the pull request, it's not a problem at all :).
