### ISSUE TITLE
Wildfire Causes a Ticking Error in Rain

### ISSUE THREAD

**Issue by andyrooney411** [Faboslav/friends-and-foes#166]
### Minecraft version information

1.20.1

### Mod loader information

Forge

### Mod loader version information

47.2.0

### Mod version information

2.0.1

### Reproduction Steps

1. Spawn Wildfire in the Overworld
2. It rains
3. The game crashes from Wildfire as the Ticking Entity

### Crash Report and latest.log

[crash-2023-12-04_11.52.25-server.txt](https://github.com/Faboslav/friends-and-foes/files/13550722/crash-2023-12-04_11.52.25-server.txt)

**Comment by Faboslav** [comment]
Should be resolved with 2.0.2 version.
