### ISSUE TITLE
Glare's Overpopulation

### ISSUE THREAD

**Issue by Excali2** [Faboslav/friends-and-foes#17]
### Minecraft version information

1.18.1

### Mod version information

1.2.2

### Expected Behavior

I installed this mod to enjoy the mobs that didn't appear in the vote, and I expected that their spawn in the world would be somewhat controlled but it is not.

### Actual Behavior

At first I found the Glare's very easy, so far everything normal. After a while I got into a cave next to the house and literally you couldn't walk because of the number of Glare's that were there.
I attach a screenshot so you can see my point of view... there were possibly about 100 Glare's in a small space
On the minimap you can see the inordinate amount of Glare's there are

### Reproduction Steps

wait by a glare's spawnpoint in a Lush cave and watch after a while

### Screenshots & files

![2022-02-06_20 32 56](https://user-images.githubusercontent.com/50200716/152698526-4af7ee58-2203-4de4-9604-73f29883f255.png)

**Comment by Excali2** [comment]
Acabo de usar el comando "kill" con los glare's.
He matado 1050 entidades... se estaba comiendo la RAM de mi servidor. a los dos minutos ya habían otros 12 en mi area
![LOG](https://user-images.githubusercontent.com/50200716/152699635-dcef026b-612b-480a-b354-77268a114b37.png)

**Comment by Faboslav** [comment]
Hello, please always check the new release first, se this is already fixed with 1.2.3 version. Also it is really weird, that your kill command killed 1050 entities, that is very far beyond any spawn limit, even with wrongly persisted glares by mod mod.
