### ISSUE TITLE
Please add the forge version 47.2.0 to requirement

### ISSUE THREAD

**Issue by SaraXianLin** [Faboslav/friends-and-foes#170]
### Minecraft version information

1.20.1

### Mod loader information

Forge

### Mod loader version information

47.2.0

### Mod version information

2.0.3

### Reproduction Steps

1.- Update the mod to 2.0.3
2.- Start the game using Forge

### Crash Report and latest.log

[latest.log](https://github.com/Faboslav/friends-and-foes/files/13628924/latest.log)
[crash-2023-12-10_13.08.17-client.txt](https://github.com/Faboslav/friends-and-foes/files/13628926/crash-2023-12-10_13.08.17-client.txt)

### Additional information

Please add the forge version requirement 47.2.0 , I am using it in a modpack and it was working fine before the latest update

**Comment by Faboslav** [comment]
Just upgrade the forge version to 47.2.17 or newer.

**Comment by Sandriell** [comment]
Additionally, please put forge version bumps into the changelog.

**Comment by Faboslav** [comment]
Hopefully today i will lower the versions required and will mention versions bumps in the changelog

**Comment by Faboslav** [comment]
Should be resolved with the `2.0.4` release.
