### ISSUE TITLE
Mooblooms are not spawning in flower forests. 

### ISSUE THREAD

**Issue by Skemati** [Faboslav/friends-and-foes#174]
### Minecraft version information

1.20.1

### Mod loader information

Fabric

### Mod loader version information

0.14.22 (Fabric)

### Mod version information

Friends&Foes mc1.20.1-2.0.6 (Fabric/Quilt)

### Expected Behavior

Mooblooms to spawn within Flower forests 

### Actual Behavior

Mooblooms don't spawn in Flower forests. 

I checked the config to see if there's anything disabled, everything is labeled as True for the Mooblooms. I decided to increase the Spawn weight to 200 for mooblooms and even after that, there aren't any mooblooms in the flower forest.  Even the Moobloom addon to friends and foes didn't work. I'm not sure if its one of the other mods I have installed, but I don't see how any of the other mods can conflict with this one. I removed Terralith temporarily to test the mod incase the world gen had some effect on the friends and foes mod but even then, no Mooblooms spawn naturally. Everything else works fine but please help me. 

### Reproduction Steps

1. Find or teleport yourself to a flower forest
2. Look for Mooblooms inside of flower forest
3. End up not finding any Mooblooms

**Comment by Faboslav** [comment]
Should be resolved with https://github.com/Faboslav/friends-and-foes/releases/tag/mc1.20.1-2.0.7

**Comment by Skemati** [comment]
It works, thanks.
