### ISSUE TITLE
[Suggestion] Make it configurable whether Illusioner would replace the vanilla one

### ISSUE THREAD

**Issue by betterworld-sjq** [Faboslav/friends-and-foes#175]
Once have enabled the illusioner,it comprehensively replaced the vanilla illusioner's behavior. So for the modpacks that have some mods allowing illusioners to spawn naturally or in structures, they all summon plenty of illusions and pour heavy firerocket attack, which applies a lot of burden. So I've been wondering whether there's a way to make it configurable whether illusioner in this mod would totally replace the vanilla one or work as an additional mob which could exist together with the vanilla illusioner(who can just summon illusions around him and can't shoot fireworks) Thanks in advance!

**Comment by Faboslav** [comment]
Hello there, yes you can set `enableIllusioner` in the config to false to disable most(hopefully all) of the illusioner features from this mod

**Comment by betterworld-sjq** [comment]
> Hello there, yes you can set `enableIllusioner` in the config to `false` to disable most(hopefully all) of the illusioner features from this mod

Yes but sir I'd like to preserve the fireworks-and-more-illusions one, not entirely ban them. Maybe I could make the tricky-to-fight one in this mod appear in a few battle structures in the modpack.

**Comment by Faboslav** [comment]
I get it, but allowing to enable/disable each feature of specific mod is hard work which is not worth at this point, also fireworks are not from this mod.
