### ISSUE TITLE
Totem of Illusion let's armor disappear

### ISSUE THREAD

**Issue by xam290** [Faboslav/friends-and-foes#177]
### Minecraft version information

1.20.1

### Mod loader information

NeoForge

### Mod loader version information

NeoForge 47.1.84

### Mod version information

2.0.6

### Expected Behavior

Totem should TP player away, give invisibility and summon clones.

### Actual Behavior

Totem activated, and armor disappeared directly. Clips from two views are uploaded. None of the effects were applied on the Player. As far as I saw there was no error in the server console.

### Reproduction Steps

1. Give enchantet netherite armor
2. Equip totem of illusion
3. Go to the nether
4. Get hit by a player a couple of times (Not sure if he got hit in the moment his armor disappeared. Could just be caused by the fire.)
5. Make sure that you are burning while trying it

### Screenshots & files

https://github.com/Faboslav/friends-and-foes/assets/83453030/87e77ab0-b4d6-42a8-8bbc-aff8681e599d

https://github.com/Faboslav/friends-and-foes/assets/83453030/cb44e158-b0a5-4018-89a6-fd60fb0e3705

**Comment by Faboslav** [comment]
Can you test this on flat planes please? Sometimes when there is not good position around the player, player will not teleport nor create illusions.
