### ISSUE TITLE
Make Totem of Illusion Drop Loottable

### ISSUE THREAD

**Issue by mahjerion** [Faboslav/friends-and-foes#178]
### Minecraft version information

1.20.1

### Mod loader information

Forge

### Mod loader version information

47.2.18

### Mod version information

2.0.6

### Expected Behavior

Configurable drops for the Illusioner. I would like to modify the loot table.

### Actual Behavior

From what I understand it's hardcoded that they always drop one - makes it a bit difficult as a modpack dev to modify the drops.

### Reproduction Steps

Look at loottables - see loottables for all entities but Illusioner.

**Comment by Faboslav** [comment]
https://github.com/Faboslav/friends-and-foes/blob/master/common/src/main/resources/data/minecraft/loot_tables/entities/illusioner.json

Illusioner is already using loot tables
