### ISSUE TITLE
Game Crashing When encountering Mooblooms on Server hosted by Essential

### ISSUE THREAD

**Issue by smolbean19** [Faboslav/friends-and-foes#179]
### Minecraft version information

1.20.1

### Mod loader information

Forge

### Mod loader version information

47.2.0 (Forge)

### Mod version information

1.3.0

### Reproduction Steps

1. Join server using Essential mod
2. Come across beekeeper hut with fenced mooblooms
3. Game crashes due to entity unable to be rendered

### Crash Report and latest.log

[latest.log](https://github.com/Faboslav/friends-and-foes/files/13848467/latest.log)
[crash-2024-01-06_00.33.24-client.txt](https://github.com/Faboslav/friends-and-foes/files/13848468/crash-2024-01-06_00.33.24-client.txt)

### Additional information

[modlist.docx](https://github.com/Faboslav/friends-and-foes/files/13848475/modlist.docx)

**Comment by smolbean19** [comment]
It only happens when on a server, I just checked survival mode and was able to spawn in mooblooms with no issue.

**Comment by Faboslav** [comment]
Please can you update both friends&foes and flowery mooblooms to the latest versions?

**Comment by smolbean19** [comment]
I updated the mods to the latest versions for 1.20.1 listed on curseforge. When joining the world through essential (I am within vicinity of the mooblooms), my game crashes and leaves this on the screen:

The game crashed whilst rendering entity in world
Error: java.lang.NullPointerException: Cannot invoke "com.faboslav.friendsandfoes.api.MoobloomVariant.getName()" because the return value of "com.faboslav.friendsandfoes.entity.MoobloomEntity.getVariant()" is null

[latest.log](https://github.com/Faboslav/friends-and-foes/files/13851592/latest.log)
[crash-2024-01-06_17.41.54-client.txt](https://github.com/Faboslav/friends-and-foes/files/13851593/crash-2024-01-06_17.41.54-client.txt)

I have provided the latest crash report and log for assistance. When the mooblooms are killed, I am able to load into the world without crashing.

**Comment by Faboslav** [comment]
I will need to do some further testing with this, but since this is only the issue with essentials i would say, the bug is on their side.

**Comment by RiskE80** [comment]
yeah my friends are having this issue too

**Comment by RiskE80** [comment]
ive tried using a server but it was way too laggy, i havent tried any essential alternatives, but i did a bit more testing and it only crashes with the flowery mooblooms mod when one is spawned

**Comment by luckyvalor** [comment]
I'm having this same problem, running a server on Aternos

**Comment by Faboslav** [comment]
Can you please try to update mod and addons(flowery mooblooms and beekeeper hut) to the newest versions? If that doesnt help, then i am out of options.

**Comment by Faboslav** [comment]
Please do reopen the issue if this still occurs, cant do anything without more info after the updates.
