### ISSUE TITLE
[Idea] Make IsIllusion nbt tag applicable to all mobs

### ISSUE THREAD

**Issue by betterworld-sjq** [Faboslav/friends-and-foes#183]
I've noticed that you apply the IsIllusion nbt tag to decide whether this illusioner is fake. Then I tried to set illagers like vindicators as illusions, it doesn't work. Would it be possible to make the tag work with all mobs? It would be quite interesting to add more illusions'types summoned by modpack-made Grand Illusioner Boss

**Comment by Faboslav** [comment]
Hello, that sounds cool, but it would be totally out of scope for this mod as i dont want to "bloat" the mod with such a features, it's more like to have some kind of library to do this if anything.
