### ISSUE TITLE
Invalide Payloard Register: moobloom_variants_sync_packet

### ISSUE THREAD

**Issue by editon96** [Faboslav/friends-and-foes#186]
### Minecraft version information

1.20.2

### Mod loader information

Fabric

### Mod loader version information

0.15.3

### Mod version information

2.0.7

### Expected Behavior

When I try to login on my Minecraft Server it get me kicked with the message: Invalide Payloard Register!

It print an Server Error I show you down.
But before 1.20.2 it works with connecting to non modded Servers with that pack to play there...

### Actual Behavior

It kick me with "Invalide Payloard Register!"

On the Server the first Error line are:

```
[16:44:25 ERROR]: Couldn't register custom payload
org.bukkit.plugin.messaging.ChannelNameTooLongException: Attempted to send a Plugin Message to a channel that was too large. The maximum length a channel may be is 64 chars (attempted 70 - 'friendsandfoes:networking/friendsandfoes/moobloom_variants_sync_packet.
```

The rest of the Error I show in an paste bin.

### Reproduction Steps

1. Download Fabric with the version Above
2. Install Fabric Api and Friend and Foes with the version Above
3. Try to join an non Modded Server e.x.: eulandia.net (my server)

### Screenshots & files

Here are the PasteBin: https://pastebin.com/wJsBCGDM with the full Error.

**Comment by Faboslav** [comment]
This is due to craftbukkit restrictions, you should create an issue there https://github.com/PaperMC/Paper/issues/10003.

**Comment by editon96** [comment]
I see thank you that you link the problem there.
Have a nice day!

**Comment by Faboslav** [comment]
No worries, closing this then :).
