### ISSUE TITLE
Ridiculous number of Glares spawning

### ISSUE THREAD

**Issue by mecha-moonboy** [Faboslav/friends-and-foes#19]
### Minecraft version information

1.18.1 in Better Minecraft Modpack

### Mod version information

1.2.2

### Expected Behavior

I expect a moderate number of Glares in caves, one every few chunks of caving.

### Actual Behavior

Hordes of Glares, can hardly walk or get out of caves at times. Very inconvenient. Forced to slay friendlies :(

### Reproduction Steps

Install Better Minecraft modpack and run Minecraft.

**Comment by mecha-moonboy** [comment]
Thank you Faboslav, doin' great work over there

**Comment by Faboslav** [comment]
Hello, please download 1.2.3 version, asi this is already fixed.
