### ISSUE TITLE
[Bug] Friends&Foes fail to create Curios API "Charm" slot

### ISSUE THREAD

**Issue by Shazuli** [Faboslav/friends-and-foes#194]
### Minecraft version information

1.20.1

### Mod loader information

Forge

### Mod loader version information

47.2.0

### Mod version information

2.0.9

### Expected Behavior

The two totems Friends&Foes adds says in the tooltip it can be placed in Curios API's "Charm". But that slot doesn't exist.

### Actual Behavior

With these two mods installed, opening Curios' GUI shows no registered slots for items when there should be at least one.

### Reproduction Steps

1. Install Forge.
2. Install Friends&Foes.
3. Install Curios API.
4. Join world.
5. Open Curios API GUI.

### Screenshots & files

![image](https://github.com/Faboslav/friends-and-foes/assets/9884180/ea938fbb-eb1b-4c64-8389-f569ae72a743)

**Comment by Faboslav** [comment]
This will be fixed with the new release soon.

**Comment by Faboslav** [comment]
Should be fixed with 2.0.10 version.
