### ISSUE TITLE
Crash at world generation

### ISSUE THREAD

**Issue by SkightMeow** [Faboslav/friends-and-foes#198]
### Minecraft version information

1.20.1

### Mod loader information

Fabric

### Mod loader version information

Forge 47.2.20

### Mod version information

1.20.1-2.0.9

### Reproduction Steps

Generate chunks

### Crash Report and latest.log

https://paste.dedimc.io/ebohujapul.properties

**Comment by Faboslav** [comment]
This is a valid issue that will be fixed with the next release :).

**Comment by Faboslav** [comment]
Should be fixed with 2.0.10 version.
