### ISSUE TITLE
Crash when using Chunk-Pregenerator-1.19-4.4.2.jar to generate nethers

### ISSUE THREAD

**Issue by Ch3225** [Faboslav/friends-and-foes#199]
### Minecraft version information

1.19.2

### Mod loader information

Forge

### Mod loader version information

43.3.8

### Mod version information

friendsandfoes-forge-mc1.19.2-2.0.0

### Reproduction Steps

Just crashes when pregenerating the chunks in nether. I guess it is a problem of your custom entity, Wildfire.
In order to cut down the resources used when players are trying to explore the map, in most cases we server owner have to use a world pregenerator like [this](https://www.curseforge.com/minecraft/mc-mods/chunkpregenerator)

### Crash Report and latest.log

[crash-2024-03-01_21.42.05-server.txt](https://github.com/Faboslav/friends-and-foes/files/14461405/crash-2024-03-01_21.42.05-server.txt)

### Additional information

If you see the Stacktrace maybe you will find the problem quickly. You might not need to reproduce how the problem happened.
Btw how can use a pregenerator to generate nether without deleting your mod:(
Your mod is really fun but this is a very deadly bug. I like ur content.
But me and my friends are waiting to play :(

**Comment by Faboslav** [comment]
Hello there, please update the mod to newest version https://github.com/Faboslav/friends-and-foes/releases/tag/mc1.19.2-2.0.9, this issue should be already fixed :)!

**Comment by Ch3225** [comment]
It works!
I updated forge and I used forge loader to "update all the mod in one click" but I don't know why this mod is not updated.
Thank you, you are my god ;)
