### ISSUE TITLE
Please add "The Great Hunger"

### ISSUE THREAD

**Issue by KMFrench1** [Faboslav/friends-and-foes#20]
I would love for you to add the mob Great Hunger that was outed voted.
here is a link to a description.
https://mcmobs.fandom.com/wiki/The_Great_Hunger#:~:text=The%20Great%20Hunger%2C%20also%20known,items%20with%20its%20huge%20mouth.

**Comment by Faboslav** [comment]
Hello there, it is already mentioned in the roadmap. Right now, i dont know yet what i will be implementing after the Iceologer.  Anyway thank you for the link with description of the mob :).
