### ISSUE TITLE
Spanish translation (I already did it)

### ISSUE THREAD

**Issue by TheLegendofSaram** [Faboslav/friends-and-foes#200]
### Minecraft version information

1.20.1

### Mod loader information

Fabric

### Mod loader version information

0.15.7

### Mod version information

2.0.9

### Expected Behavior

A complete spanish translation

### Actual Behavior

Is preatty incomplete, but i already did the translation, here is the file, is in th mexican spanish format

### Reproduction Steps

idk

### Screenshots & files

[friendsandfoes es_mx.zip](https://github.com/Faboslav/friends-and-foes/files/14465273/friendsandfoes.es_mx.zip)

**Comment by Daralexen05** [comment]
I have an es_es.json for the most recent version since November 2023. I need to have it published though. I just fixed the Spanglish and changed the name of Iceologer to the official name used in the Castilian Spanish version of Minecraft Dungeons.

**Comment by Faboslav** [comment]
Hello there, I will try to do some kind of small release with bug fixes and updated translations soon.

**Comment by Daralexen05** [comment]
> Hello there, I will try to do some kind of small release with bug fixes and updated translations soon.

Will both es_es and es_mx be included? I just need to be allowed to make pull requests here in order to publish my localisations.

**Comment by Faboslav** [comment]
I can include both, you are allowed to create the pull request, you need to fork the repo first, then create a pull request :).

**Comment by Faboslav** [comment]
Mentioned es_mx translations will be released soon, i am closing this for now, thank you for the translations!

**Comment by TheLegendofSaram** [comment]
Yeah man, dont worry, thank you for working in these amazing mod!!

> Mentioned es_mx translations will be released soon, i am closing this for now, thank you for the translations!
