### ISSUE TITLE
Glare entity icon is unreasonably large on Xaero's Minimap

### ISSUE THREAD

**Issue by Daralexen05** [Faboslav/friends-and-foes#206]
### Minecraft version information

1.20.1

### Mod loader information

Forge

### Mod loader version information

Latest release for 1.20.1

### Mod version information

Friends&Foes: friendsandfoes-forge-mc1.20.1-2.0.10.jar Xaeros Minimap: v24.0.3 for Forge 1.20(.1)

### Expected Behavior

The entity icons should either appear as yellow dots, or average sized mob heads. Iceologer, Moobloom, Rascal, Beekeeper Villager/Zombie Villager, Wildfire, Glare, Great Hunger all appear on the map with unique icons while Copper and Tuff Golem appear as standard yellow dots for most modded entities.

### Actual Behavior

The Glare icon is unreasonably large on the minimap and covers too much space on the map when it is present. This makes it difficult to see other entitles or players nearby the Glare on the minimap.

### Reproduction Steps

1. Have both mods installed and enable mob icons for the minimap
2. Spawn Glares

**Comment by Faboslav** [comment]
Hello, the only solution for this would be custom head icon and i dont have currently have resources and skill for that.

**Comment by Daralexen05** [comment]
> Hello, the only solution for this would be custom head icon and i dont have currently have resources and skill for that.

As you can see, the icon is way too big for the Glare in my opinion. It completely covers my house and another building on the minimap. This also makes it a little difficult to see hostile mobs on the minimap in a Lush Cave. I use a resource pack that adds icons for modded entities from various mods. Said resource pack includes your mod in it for adding icons for Copper and Tuff Golem. Maybe I could request the creator of the pack to include a fixed icon for the Glare in the next release of it.
![2024-04-04_13 35 36](https://github.com/Faboslav/friends-and-foes/assets/144989721/7899dfb7-dddf-4b89-8899-3214b2831108)

**Comment by Faboslav** [comment]
Maybe if author wanted i can include this in the mod, but until then best solution would be to add custom icons for the "big mobs", sorry for the troubles :).

**Comment by NolanHewitt** [comment]
BTW, you can shrink the size of any icon for the minimap by adding a transparent border around the image. The larger the border the smaller the image on the minimap. It’s pretty easy to do yourself with any image editor if you don’t mind manually putting in the work.
