### ISSUE TITLE
Mauler spawns with incorrect biome skin in Modern Beta Deserts

### ISSUE THREAD

**Issue by Daralexen05** [Faboslav/friends-and-foes#209]
### Minecraft version information

1.20.1

### Mod loader information

Forge

### Mod loader version information

Forge 47.2.20

### Mod version information

Friends&Foes: friendsandfoes-forge-mc1.20.1-2.0.10 Modern Beta: modern-beta-fabric-6.4+1.20.jar

### Expected Behavior

Maulers that spawn in Beta Desert biomes use their proper desert skin.

### Actual Behavior

The Mauler spawns with its Savannah skin in Beta Deserts.

### Reproduction Steps

1. Install Friends&Foes, Modern Beta, Syntra Connector, and all of their dependencies. 
2. Create a new world with Beta 1.7.3 world generation.
3. Look for a beta desert biome and wait for a Mauler to spawn with its Savannah biome skin.

**Comment by Faboslav** [comment]
You need to report this to the other mod, they should fix their biome tags, tag of `has_desert_mauler.json` based on file `has_desert_mauler.json` has the following content:
```
{
	"values": [
		"minecraft:desert",
		{
			"id": "#c:desert",
			"required": false
		},
		{
			"id": "#forge:is_desert",
			"required": false
		}
	]
}
```

opposite to `has_savanna_mauler`:

```
{
	"values": [
		"#minecraft:is_savanna",
		{
			"id": "#forge:is_savanna",
			"required": false
		},
		{
			"id": "#c:savanna",
			"required": false
		}
	]
}
```

**Comment by Daralexen05** [comment]
> You need to report this to the other mod, they should fix their biome tags, tag of `has_desert_mauler.json` based on file `has_desert_mauler.json` has the following content:
> 
> ```
> {
> 	"values": [
> 		"minecraft:desert",
> 		{
> 			"id": "#c:desert",
> 			"required": false
> 		},
> 		{
> 			"id": "#forge:is_desert",
> 			"required": false
> 		}
> 	]
> }
> ```
> 
> opposite to `has_savanna_mauler`:
> 
> ```
> {
> 	"values": [
> 		"#minecraft:is_savanna",
> 		{
> 			"id": "#forge:is_savanna",
> 			"required": false
> 		},
> 		{
> 			"id": "#c:savanna",
> 			"required": false
> 		}
> 	]
> }
> ```

I did report this about mobs from mods spawning strangely in Modern Beta Biomes. I have also seen Rabbits spawn in these Deserts without their normal creamy skins.

**Comment by Daralexen05** [comment]
Is there anything that I can do to fix this until Modern Beta fixes it? I have also noted that other mobs with biome-dependent skins such as Rabbits, Frogs, Mantis Shrimp (Alex's Mobs), 1.20.5 Wolves (Backported Wolves) do not spawn with correct skins. Only the default Frogs, Mantis Shrimp, and Wolves spawn.

**Comment by Faboslav** [comment]
I am not sure, maybe you can correct theirs biome tags witth a datapack.
