### ISSUE TITLE
Totem of Illusion did not save me from Iceologer's Ice Chunk

### ISSUE THREAD

**Issue by Daralexen05** [Faboslav/friends-and-foes#212]
### Minecraft version information

1.20.1

### Mod loader information

Forge

### Mod loader version information

Forge 47.2.20

### Mod version information

Friends&Foes: friendsandfoes-forge-mc1.20.1-2.0.10

### Expected Behavior

Totem of Illusion in my off-hand would save me from the Ice Chunk falling on my head

### Actual Behavior

Ice Chunk kills me as if I were not holding a totem.

### Reproduction Steps

1. Have a Totem of Illusion in your off-hand
2. Find or spawn an Iceologer
3. Watch the Iceologer kill you as if you did not have a totem in your off-hand.

**Comment by Faboslav** [comment]
Both of the new totems, will NOT prevent death, so if you take fatal damage, that is it.
