### ISSUE TITLE
Glare Crashes

### ISSUE THREAD

**Issue by OvenProofBody** [Faboslav/friends-and-foes#214]
### Minecraft version information

1.19.2

### Mod loader information

Fabric

### Mod loader version information

Fabric 0.15.7

### Mod version information

2.0.10

### Reproduction Steps

Unknown specfics
All that is known is there was 3 glares in one room in 1 chunk the room was brightly lit 

### Crash Report and latest.log

[server199062_8_May_2024_1_43_23.zip](https://github.com/Faboslav/friends-and-foes/files/15244317/server199062_8_May_2024_1_43_23.zip)

**Comment by Faboslav** [comment]
This is not error from Friends&Foes, you should report this to the slab mod (ExtraSlabBlock) or whatever that name is.

**Comment by OvenProofBody** [comment]
got it
