### ISSUE TITLE
The Glare's texture breaks in resource pack

### ISSUE THREAD

**Issue by Daralexen05** [Faboslav/friends-and-foes#215]
### Minecraft version information

1.20.1

### Mod loader information

Forge

### Mod loader version information

Forge 47.2.20

### Mod version information

Friends&Foes: friendsandfoes-forge-mc1.20.1-2.0.10

### Expected Behavior

The Glare's texture would correspond to the one that I made for it with a resource pack.

### Actual Behavior

The Glares texture is broken when loaded in game with the Resource Pack enabeled

### Reproduction Steps

1. Use my Friends&Foes Programmer Art Resource Pack (Still a WIP)
2. Spawn a Glare

### Screenshots & files

![glare](https://github.com/Faboslav/friends-and-foes/assets/144989721/e44c5872-516d-4e53-8e56-f0e1fe516b8c)
The texture
![flowering_glare](https://github.com/Faboslav/friends-and-foes/assets/144989721/70649e60-2ef7-4984-9cf7-047194a5b5a8)
Tamed texture

![2024-05-15_00 44 41](https://github.com/Faboslav/friends-and-foes/assets/144989721/4348959a-2345-4e7a-82b0-c79bf81cc8a8)
When loaded in-game

**Comment by Faboslav** [comment]
You are using old glare textures, these are the new ones:

![flowering_glare](https://github.com/Faboslav/friends-and-foes/assets/14179066/ab55c829-6d91-49eb-8ab8-54915aabce2f)
![glare](https://github.com/Faboslav/friends-and-foes/assets/14179066/02800b63-53e5-43ed-a432-76a9e97e953c)

**Comment by Daralexen05** [comment]
> You are using old glare textures, these are the new ones:
> 
> ![flowering_glare](https://private-user-images.githubusercontent.com/14179066/330736378-ab55c829-6d91-49eb-8ab8-54915aabce2f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4Mzg5MTYsIm5iZiI6MTcxNTgzODYxNiwicGF0aCI6Ii8xNDE3OTA2Ni8zMzA3MzYzNzgtYWI1NWM4MjktNmQ5MS00OWViLThhYjgtNTQ5MTVhYWJjZTJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDA1NTAxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyOGYxZTZkMDg3ZmI4MDg5ZTU1NGU1MjgzNDRjMDdmNjkzZTJiOGE4ZDBkNTNkNGJkMjVhOTUxZmYzNjZiMjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xRysBJ6ZbaGJmCzhm2vXFeRKKUKZo3aXDHHQIfW5LqA) ![glare](https://private-user-images.githubusercontent.com/14179066/330736428-02800b63-53e5-43ed-a432-76a9e97e953c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4Mzg5MTYsIm5iZiI6MTcxNTgzODYxNiwicGF0aCI6Ii8xNDE3OTA2Ni8zMzA3MzY0MjgtMDI4MDBiNjMtNTNlNS00M2VkLWE0MzItNzZhOWU5N2U5NTNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDA1NTAxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2YWE0NmJkZTQ2ODU2ODk2MzEwNmU1OGRjZTdkZjIzMzdhYWU5OWVlOTBhNzZmYzc3YWQxNDRlMDJhOTE0ZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AiAmwStwlwQ5L7R95nxTrFnccN62miCYttfpUVw3OlM)

![2024-05-15_15 11 36](https://github.com/Faboslav/friends-and-foes/assets/144989721/27bbb24c-1016-43aa-b9a5-121dffd69e6e)
It works now. I had no idea that there was a texture change. I guess I will need to either make two versions for older versions of the mod, or specifically state that the pack only supports newer versions.
