### ISSUE TITLE
Duplication with Rascal, using Carry on

### ISSUE THREAD

**Issue by FootManDo** [Faboslav/friends-and-foes#217]
### Minecraft version information

1.20.1

### Mod loader information

Forge

### Mod loader version information

47.2.0

### Mod version information

2.0.10

### Expected Behavior

When finding the Rascal for the 3rd time they disappear after giving you an item inside of a bundle.

### Actual Behavior

If using the Carry On mod, picking up the Rascal after they give you the bundle but before they disappear, they reset. Allowing you to find them 3 times again for a new reward. I'm not sure if this is something that can be fixed on this end however I thought to bring it to light as it's a possible thing to do and very easy to replicate.

### Reproduction Steps

Find a Rascal 2 times
On the 3rd after they give you the bundle pick them up
Place them back down and repeat
Each time it's a different reward

**Comment by Faboslav** [comment]
This will be fixed with the next release, rascal will not give rewards anymore.
