### ISSUE TITLE
[Possible bug} The Iceologer can naturally spawn in cold biomes like any other hostile mob

### ISSUE THREAD

**Issue by Daralexen05** [Faboslav/friends-and-foes#219]
### Minecraft version information

1.20.4

### Mod loader information

Fabric

### Mod loader version information

Fabric Loader 0.15.11

### Mod version information

friendsandfoes-fabric-mc1.20.4-2.0.10.jar

### Expected Behavior

The wiki states that Iceologers only spawn in their cabins and in raids. If not, then the Wiki should state that they are a rare natural spawn at night in cold biomes.

### Actual Behavior

I found an Iceologer in my construction site in a Beta Tundra biome from Modern Beta. Said construction site is far away from a Cabin and there were no raids. I also saw one 5 in-game days prior on my minimap in a Beta Taiga biome from the same mod.

### Reproduction Steps

1. Be in a cold biome at night (Does not specifically need to be Modern Beta's cold biomes)
2. Wait for an Iceologer to spawn (Either change the difficulty to Hard or install another mod like Enhanced Celestials and enable a Blood Moon or Super Blood Moon in order to make it spawn faster)

### Screenshots & files

![2024-05-20_19 35 58](https://github.com/Faboslav/friends-and-foes/assets/144989721/7c8cf010-e24d-4524-b7cc-59a414dd678c)

**Comment by Faboslav** [comment]
Hello there, i probably need to document this somewhere, but iceologers can spawn with patrol alike logic in the cold biomes, and also the illusioner can spawn with patrol alike logic in taiga biomes.
