### ISSUE TITLE
Config being ignored

### ISSUE THREAD

**Issue by UnknownVariables-here** [Faboslav/friends-and-foes#222]
### Minecraft version information

1.20.1

### Mod loader information

Forge

### Mod loader version information

47.2.20

### Mod version information

2.0.10

### Expected Behavior

Glares should be disabled. after I've shut down the server set the "enableGlare" and "enableGlareSpawn" to false, then start it back up.
![image](https://github.com/Faboslav/friends-and-foes/assets/77986568/74b503b5-a610-40c4-8414-1d597ee1556c)

### Actual Behavior

Glares are still spawning. Ive setup a loop to kill them every minute and normally about 15-18 are there and they show up in the spark reports.
![image](https://github.com/Faboslav/friends-and-foes/assets/77986568/0adac65d-900c-44ef-8641-df0656304dfe)

### Reproduction Steps

Setup server on 1.20.1 Forge 47.2.20
Add friends and foes 2.0.10
Disable glare
Start server
Setup command block to run " kill @e[type=friendsandfoes:glare] " on loop
run around
Notice glares being killed from command block broadcast to op.

**Comment by Faboslav** [comment]
Well, due to forge limitations, it's not currently possible to connect config setting to the forge specific json files, i may have some workaround, but we will see.

**Comment by Faboslav** [comment]
This will be fixed with the next release.
