### ISSUE TITLE
Wiki Link Broken

### ISSUE THREAD

**Issue by AriaElidove** [Faboslav/friends-and-foes#223]
### Minecraft version information

N/A

### Mod loader information

Fabric

### Mod loader version information

N/A

### Mod version information

N/A

### Expected Behavior

I don't know how to let you know this or modify it, but the Totem of Illusion wiki page has a broken link shown below. It's just missing a `)` after the bad omen wiki page link. 

![image](https://github.com/Faboslav/friends-and-foes/assets/144502047/acb0fa43-816c-4e62-bcf8-aacf86de3a86)

### Actual Behavior

N/A

### Reproduction Steps

N/A

**Comment by Faboslav** [comment]
Thank you, its fixed now :).
