### ISSUE TITLE
[BUG 1192] something wrong with 'friendsandfoes:totem_of_illusion'/skeleton ai

### ISSUE THREAD

**Issue by 2929762171** [Faboslav/friends-and-foes#224]
### Minecraft version information

1.19.2

### Mod loader information

Forge

### Mod loader version information

43.3.7

### Mod version information

2.0.10

### Expected Behavior

reset ai after the effect expires

### Actual Behavior

Keep attacking the air

### Reproduction Steps

activate Totem of Illusion by skeleton

### Screenshots & files

![image](https://github.com/Faboslav/friends-and-foes/assets/98941945/2c5a10d1-b333-4051-995f-ae50350cd085)

**Comment by 2929762171** [comment]
another render issue,
press F10 or  reborn after death will cause entities renderring failure, looks like they are all invisible

**Comment by 2929762171** [comment]
> another render issue, press F10 or reborn after death will cause entities renderring failure, looks like they are all invisible

ignore this, caused by another mod, it limits the number of entity rendering.

**Comment by Faboslav** [comment]
If's that so, can i close the issue?

**Comment by 2929762171** [comment]
> If's that so, can i close the issue?

skeleton ai still the main problem

**Comment by Faboslav** [comment]
I tried with skeleton, and skeleton reacts properly, what should be the problem?

**Comment by Faboslav** [comment]
Tested a lot of things, skeleton AI is fine, if you want, you can reopen the issue with more specific details of the problem related to the AI.

**Comment by 2929762171** [comment]
> Tested a lot of things, skeleton AI is fine, if you want, you can reopen the issue with more specific details of the problem related to the AI.

here
https://github.com/Faboslav/friends-and-foes/assets/98941945/02a99804-4ac0-42ef-b2be-098bb16d745f


https://github.com/Faboslav/friends-and-foes/assets/98941945/5de40f18-ef94-4e7a-90b3-934281ecca4f
