### ISSUE TITLE
Totem of Illusion doesn't teleport the player or apply invisibility in the off-hand

### ISSUE THREAD

**Issue by Roadhog360** [Faboslav/friends-and-foes#225]
### Minecraft version information

1.20.1

### Mod loader information

Forge

### Mod loader version information

Forge 47.3.1

### Mod version information

2.0.10

### Expected Behavior

When holding the totem in either hand, your player isn't teleported away, de-aggroed from any monsters and invisibility is not applied. The clones do still appear however.

### Actual Behavior

None of the above occurs

### Reproduction Steps

Hold the totem in the off-hand
Let a mob attack you until the totem activates

**Comment by Faboslav** [comment]
Are you sure this happens every time or any time? I just tested it and i am teleported and also invisible. Can you try this alone just with Friends&Foes?

**Comment by Faboslav** [comment]
If you are in a "bad position", teleport can be unsuccessful, and invisibility wont get applied, that can happen too, but it should not be based on if the item is in off hand or not.

**Comment by Roadhog360** [comment]
I guess it was a coincidence. I will test it alone later. I was in a forest which may have caused the unsuccessful attempt. Are you not trying multiple times?

**Comment by Faboslav** [comment]
I enhanced a logic little bit, so player will always get teleported with at least one available and valid position.
