### ISSUE TITLE
Wildfire Crown stacks to 64 and has no texture when worn

### ISSUE THREAD

**Issue by StunfMC** [Faboslav/friends-and-foes#227]
### Minecraft version information

1.20.6

### Mod loader information

Fabric

### Mod loader version information

0.15.11

### Mod version information

2.0.11

### Expected Behavior

The Wildfire Crown should not stack to 64 and have a texture when worn.

### Actual Behavior

The Wildfire Crown stacks to 64 and does not have a texture when worn.

### Reproduction Steps

Shift-click a Wildfire crown from the creative inventory, and wear one to see that there is no texture when worn.

**Comment by Faboslav** [comment]
You are correct, i switched things up while porting to 1.20.6, this will be fixed with the next release.
