### ISSUE TITLE
WildFire Crown is broken

### ISSUE THREAD

**Issue by KekDog** [Faboslav/friends-and-foes#230]
### Minecraft version information

1.21

### Mod loader information

Fabric

### Mod loader version information

0.15.11 Fabric

### Mod version information

2.0.11

### Expected Behavior

.

### Actual Behavior

WildFire Crown dont have texture

### Reproduction Steps

Put on wildfire crown

### Screenshots & files

![2024-07-06_21 22 50](https://github.com/Faboslav/friends-and-foes/assets/174894520/73b60a2e-74e5-4893-8b0a-5ee64b1f8c74)
![2024-07-06_21 23 03](https://github.com/Faboslav/friends-and-foes/assets/174894520/240e70a7-ec46-4983-867c-39b550f0ba1a)

**Comment by Faboslav** [comment]
Will be fixed with next release.
