### ISSUE TITLE
[1.21-Neo] Crash running around world past NeoForge version .74 and above.

### ISSUE THREAD

**Issue by Gbergz** [Faboslav/friends-and-foes#231]
### Minecraft version information

1.21

### Mod loader information

NeoForge

### Mod loader version information

21.0.78

### Mod version information

2.0.12

### Reproduction Steps

Go into a world
run around, or open creative tab.
crash.

### Crash Report and latest.log

https://gist.githubusercontent.com/Gbergz/29e4514a2d282abb5ee2df9b64c7bdc6/raw/2226543fdb45856c49aa282bf4df0cd6c89c83f9/gistfile1.txt

### Additional information

Basically it.

**Comment by Faboslav** [comment]
You can use older NeoForge version, since its in beta stage, breaking changes may happen.

**Comment by Faboslav** [comment]
Fix will be released but probably not this week.

**Comment by Gbergz** [comment]
> You can use older NeoForge version, since its in beta stage, breaking changes may happen.

Yep, that's what I am doing, just testing newer Forge version to see which mods are broken and then I report it.

> Fix will be released but probably not this week.

Sweet!

**Comment by Faboslav** [comment]
Should be fixed.
