### ISSUE TITLE
Totem of Undying does not proc from Charm slot / No option to disable Trinkets integration

### ISSUE THREAD

**Issue by Window0** [Faboslav/friends-and-foes#232]
### Minecraft version information

1.20.1

### Mod loader information

Fabric

### Mod loader version information

Irrelevant

### Mod version information

2.0.12 for Fabric

### Expected Behavior

This mod has a Trinkets integration which enables putting Totems of Undying in one's Charm slot.
However, there is no functionality for Totems of Undying actually working from that slot.

Players will put their Totems in this slot and assume that the Totem will save them from death, and then be confused why the Totem didn't activate.

I can suggest 3 possible solutions to this:
1. Remove the ability to put Totems of Undying in the Charm slot
2. Make wether Totems of Undying can be put in the Charm slot toggleable in the config
3. Add functionality for Totems of Undying in the Charm slot

### Actual Behavior

You die when you are killed

### Reproduction Steps

1. Put Totem of Undying in Charm slot
2. die

### Screenshots & files

<img width="518" alt="Screenshot 2024-07-09 215710" src="https://github.com/Faboslav/friends-and-foes/assets/48733009/8b84759b-3ebb-424c-9841-4a0f53679a49">

**Comment by Faboslav** [comment]
Will be "fixed" in the next release.
