### ISSUE TITLE
[BUG] Lightning on Copper Golems jitters movement and plays death animation 1.21

### ISSUE THREAD

**Issue by makumaku1974** [Faboslav/friends-and-foes#234]
### Minecraft version information

1.21

### Mod loader information

Fabric

### Mod loader version information

0.16.0

### Mod version information

2.0.13

### Expected Behavior

Copper Golem should act normal after getting strucked by lighning

### Actual Behavior

Plays Death Animation when getting strucked by lightning and jitters like hell 

### Reproduction Steps

1. summon a oxidized copper golem
2. summon lightning
3. Let the magic begins

### Screenshots & files

![image](https://github.com/user-attachments/assets/16ecf0fa-56c7-4843-9e1b-b12abd26bc3d)
screenshot of a copper golem jittering

**Comment by Faboslav** [comment]
Summon, you mean by building, i just tried that, nothing is happening, can you try this only with Friends&Foes?

**Comment by makumaku1974** [comment]
> Summon, you mean by building, i just tried that, nothing is happening, can you try this only with Friends&Foes?

summon lightning....

**Comment by makumaku1974** [comment]
i guess i have to check it again and remove some other mods. brb

**Comment by makumaku1974** [comment]
Did you checked the copper golem when charged with lightning?

**Comment by Faboslav** [comment]
Yes, i build the golem then summoned the lightning

**Comment by makumaku1974** [comment]
> Yes, i build the golem then summoned the lightning, sorry for the miss understanding

just keep this on for now ill be checking out the problem.

**Comment by makumaku1974** [comment]
> Yes, i build the golem then summoned the lightning, sorry for the miss understanding

Hi! I found the issue. It is related with this 3 mods btw. I am not sure what causes it but it is related to them since the jitter is removed.
![image](https://github.com/user-attachments/assets/40651579-187f-43f1-9d40-01aeb79e4d29)

**Comment by makumaku1974** [comment]
![image](https://github.com/user-attachments/assets/571c6fa1-0f06-4fb0-8432-8a1ff9e53e25)
![image](https://github.com/user-attachments/assets/47e47c90-1ad8-4245-b854-cdf0c1bfb734)

**Comment by Faboslav** [comment]
What about other mobs from Friends&Foes with these three mods?

**Comment by makumaku1974** [comment]
> What about other mobs from Friends&Foes with these three mods?

it's only the copper golem though, Anyway this is due to the error with SASSOT's mixin and two other mods called Crital and Penomior but I'll be checking it yet again.

**Comment by Faboslav** [comment]
Is there already another issue created on some of the mentioned mods?

**Comment by makumaku1974** [comment]
> Is there already another issue created on some of the mentioned mods?

Not yet, but ill report it to you if problems arise.

**Comment by makumaku1974** [comment]
Hey! This is already fixed imma close it now.

**Comment by Faboslav** [comment]
How was this fixed, can you link the issue or something please?

**Comment by makumaku1974** [comment]
> How was this fixed, can you link the issue or something please?

So sorry but I couldn't recreate the problem due to having 500+ mods so i reset everything back to zero anyway.
