### ISSUE TITLE
Bee's won't leave bamboo beehive | invalid for ticking (just the bamboo ones, the rest for some reason. . . are fine)

### ISSUE THREAD

**Issue by Ynaught** [Faboslav/friends-and-foes#235]
### Minecraft version information

1.21

### Mod loader information

Fabric

### Mod loader version information

0.16.0

### Mod version information

2.0.14

### Expected Behavior

. . . bees to leave the beehive at some point.

### Actual Behavior

They stay in the hive permanently.
I cannot confirm but I think the hive honey updater isn't updating either. I forget if honey updates on entering or exiting. . . if it's on exiting, it makes sense why the honey counter is at 0.

### Reproduction Steps

- Place F&Fs bamboo beehive.
- Spawn bee.
- Bee enters F&F bamboo beehive.
- Wait for nothing to happen after entering and watch as bee will not exit hive even after multiple in-game days.

**Comment by Ynaught** [comment]
Update: tested it in a creative world. . . testing so far was on the birch beehive and the bamboo beehive. . . Birch seems fine but bamboo is not. Going to test all F&F variants now. . . how strange.

**Comment by Ynaught** [comment]
Alright I tested every other Beehive. . . Birch, Cherry, Jungle, Mangrove, Dark Oak, Spruce, Warped, Crimson. . . let it run for a couple of in-game days. . . it's literally just bamboo. . . and that's weird. . . cause there shouldn't be anything unique to the bamboo variant other than a texture. . . so is like, one of the texture stages missing or something???

I ran bamboo multiple times to be sure:

![image](https://github.com/user-attachments/assets/3cde0202-b40c-4ab8-96df-7f1cbfcb4fca)

I even tested for multiple conditions as well relating to smoked and unsmoked:
![image](https://github.com/user-attachments/assets/5e0d3543-d33f-4e73-ba39-9f12d1d661a4)

Bamboo bees just seem to be shut-in bees who wanna hang on the couch all day playing beecraft and never leave the hive. Honestly, I blame bee culture. Beeing on bamboo too long just isn't good for your sense of adventure.

**Comment by Ynaught** [comment]
I found the issue I think:

Block entity minecraft:beehive @ class_2338{x=1, y=1, z=1} state Block{friendsandfoes:bamboo_beehive}[facing=west,honey_level=0] invalid for ticking:


It doesn't say that for any of the other hives. Seems to be a class-related issue?

**Comment by Faboslav** [comment]
Thank you very much for all the context and useful info! I need to first release some bug fixes for Variants&Ventures, but I will look into it this week for sure.

**Comment by Faboslav** [comment]
This should be fixed with the new release, please do let me know in case of any problem :).

**Comment by Ynaught** [comment]
Well I have notice that the bee keepers aren't restocking what they sell. I have only tested it on the bamboo behives. So I cannot confirm if it's related or not.
