### ISSUE TITLE
Illusioner won't drop Totem of Illusion

### ISSUE THREAD

**Issue by Turtle029** [Faboslav/friends-and-foes#236]
### Minecraft version information

1.21

### Mod loader information

Fabric

### Mod loader version information

0.15.11 (Fabric)

### Mod version information

2.0.13

### Expected Behavior

Illusioner should drop Totem of Illusion

### Actual Behavior

Illusioner does not drop Totem of Illusion

### Reproduction Steps

I find an Illusioner cabin, I kill the Illusioner, does not drop Totem of Illusion.      Drops in creative but not survival

**Comment by Faboslav** [comment]
Are you sure? I just tested with fabric, and it drops the totem in survival mode.

**Comment by Turtle029** [comment]
I kill them all the time in raids and they don't drop the totems.

**Comment by Faboslav** [comment]
Can you please try to isolate the issue somehow? I cant reproduce this at all, also can you try with the `2.0.15` mod version?

**Comment by Faboslav** [comment]
Please do reopen if you have any more information or context.
