### ISSUE TITLE
Totem of Illusion and freezing dont work

### ISSUE THREAD

**Issue by Yo-Snowpro** [Faboslav/friends-and-foes#239]
### Minecraft version information

1.21

### Mod loader information

Fabric

### Mod loader version information

0.16.00 Fabric

### Mod version information

fabric-mc1.21-2.0.15

### Expected Behavior

The totems will be used and do there unique abilities

### Actual Behavior

The totems dont get used and just make you die insted

### Reproduction Steps

1. Go into creative
2. Give yourself both totems
3. put one in your offhand
4. fly up to a lethal height
5. go into survival

### Screenshots & files

![2024-07-24_19 28 19](https://github.com/user-attachments/assets/8d0a8404-35b4-407c-80b5-72fca0f94cac)

**Comment by Faboslav** [comment]
Totem trigger is not death:
- https://github.com/Faboslav/friends-and-foes/wiki/Totem-of-Freezing
- https://github.com/Faboslav/friends-and-foes/wiki/Totem-of-Illusion

**Comment by Yo-Snowpro** [comment]
oh
