### ISSUE TITLE
[1.18.2] Crash when randomly exploring.

### ISSUE THREAD

**Issue by Gbergz** [Faboslav/friends-and-foes#24]
### Minecraft version information

1.18.2

### Mod loader information

Forge

### Mod loader version information

40.0.34

### Mod version information

1.3.1

### Reproduction Steps

Not sure exactly, but:

1. Explore world. (I was about to enter a cave, not sure if its related at all.)
2. Walk.
3. Crash. 

### Crash Report and latest.log

Crash-Report: https://gist.github.com/Gbergz/185bae38f600df32b8d060db8ea6db81
Latest.log: https://gist.github.com/Gbergz/41bb3fdb71aab6ebc31981549a257cf0

### Additional information

List of other mods should be in the crash report file listed above.

**Comment by Faboslav** [comment]
Hello, thank you for your report. 

Can you please test for me one more thing in context of the modpack that you are using?

Create new world in creative, go somewhere, for example to the plains biome, place oak beehive, spawn moobloom, spawn bee. Does the bee try to pollinate the moobloom?

**Comment by Gbergz** [comment]
Hey,
Just tested and it doesn't seem to try and pollinate the moobloom.

**Comment by Faboslav** [comment]
Thanks, i will try to release new version with a fix today :).
