### ISSUE TITLE
Wildfire should take extra damage from freezing just like other hot mobs.

### ISSUE THREAD

**Issue by NolanHewitt** [Faboslav/friends-and-foes#240]
Hot mobs like blazes, magma cubes, and striders, take extra damage from freezing. The wildfire should be given the freeze_hurts_extra_types tag just like those mobs have for consistency.

**Comment by Faboslav** [comment]
Hello, that's a very good point, this will be added with the next release :).

**Comment by Faboslav** [comment]
Should be added with the 2.0.16 version of the mod.
