### ISSUE TITLE
Glares won't breed

### ISSUE THREAD

**Issue by Tinnedfoil906** [Faboslav/friends-and-foes#241]
### Minecraft version information

1.21

### Mod loader information

Fabric

### Mod loader version information

0.16.0

### Mod version information

2.0.15

### Expected Behavior

Glares should breed after giving them glow berries

### Actual Behavior

Glares don't breed after giving them glow berries

### Reproduction Steps

1. Tame 2 glares
2. Use glow berries on the 2 glares

**Comment by Faboslav** [comment]
Hello there, thanks for the report, i found the issue, fix will be released soon.

**Comment by Faboslav** [comment]
Should be working again with the 2.0.16 version of the mod.
