### ISSUE TITLE
Mauler - Infinite feed with certain enchanted items and weird behavior with XP bottles.

### ISSUE THREAD

**Issue by Andresgsr** [Faboslav/friends-and-foes#244]
### Minecraft version information

1.20.1

### Mod loader information

Fabric

### Mod loader version information

0.16.0

### Mod version information

2.0.16

### Expected Behavior

The Mauler eats a SINGLE enchanted item and grows a bit

### Actual Behavior

When giving Maulers an enchanted sword, it eats it and grows slightly. However, when you give them an enchanted Netherite pants (for example), you can spam click the interact key (even without other enchanted gear at hand) to grow them indefinitely. 

### Reproduction Steps

1. Grab enchanted gear (pants/chestplate,etc)
2. Click on the mauler indefinitely 

### Screenshots & files

https://github.com/user-attachments/assets/35333f52-4d06-4e3a-b782-8912d321745e

**Comment by Faboslav** [comment]
Hello, i will need to take a look at this, thanks for the report.

**Comment by Faboslav** [comment]
Yeah, this was really easy to reproduce and will be fixed with 2.0.17 version, thanks!
