### ISSUE TITLE
Trinket's Charm Slot - Not usable

### ISSUE THREAD

**Issue by Ethereal-Sound** [Faboslav/friends-and-foes#247]
### Minecraft version information

1.21

### Mod loader information

Fabric

### Mod loader version information

0.16.3

### Mod version information

2.0.16

### Expected Behavior

The mod enables the "charm" slot from Trinkets, but the totems are unusable in that slot.

### Actual Behavior

Can't place totems in Charm slot.

### Reproduction Steps

1. Install Trinkets and Friends&Foes
2. Try to place Totem in charm slot
3. Unable to

**Comment by Faboslav** [comment]
Yeah, its present in the datapack, but at the time of the release, trinkets were not for 1.21 version i think

**Comment by Faboslav** [comment]
This will be fixed with 2.0.17 version, thanks!
