### ISSUE TITLE
Obscure issue with Beekeeper Trades

### ISSUE THREAD

**Issue by BioMasterZap** [Faboslav/friends-and-foes#250]
### Minecraft version information

1.20.4

### Mod loader information

Fabric

### Mod loader version information

Fabric 0.16.2

### Mod version information

v2.0.16

### Expected Behavior

The Beekeeper trades with right-clicked.

### Actual Behavior

The Beekeeper cannot be traded when right-clicked and just does that headshake thing. This does not happen with Friends&Foes by itself. 

### Reproduction Steps

After a lot of trial and error, I think I figured out the combination of mods causing it. For Fabric 0.16.2 for 1.20.4 with Fabric API v0.97.1 if Friends&Foes v2.0.16 is used alongside Crossbow Expansion v1.2.1, GlitchCore v1.0.0.59, AND Vanilla's experimental Villager Trade Rebalance Data Pack, the Beekeeper will not be given trades. If any of those three are removed/disabled, the Beekeeper will have trades. 

To Reproduce:
1. Prepare an instance of Fabric 0.16.2 for 1.20.4.
2. Add Fabric API v0.97.1, Friends&Foes v2.0.16, Crossbow Expansion v1.2.1, and GlitchCore v1.0.0.59 to the Mods Folder.
3. Create a New World, click the "More" tab at the top right, select Experiments, and toggle "Villager Trade Rebalance" to "On", then click "Done" and "Create New World".
4. Find a Beekeeper (or place a Beehive and Spawn one in) and attempt to right-click it to Trade once it has taken the Profession.

If this is repeated without enabling the "Villager Trade Rebalance" or with Crossbow Expansion or GlitchCore removed from the Mods Folder, the Beekeeper will trade. A combination of any two of the three is fine; it is only when all three are present that the issue seems to occur.

### Screenshots & files

Using CraftTweaker to get the Entity NBT, when the bug occurs instead of the normal "Offers: {Recipes:" the Beekeeper does not have "Offers" in their Info at all. I also saw ""friendsandfoes:beekeeperOffers": {Recipes: []}," in place of the normal "Offers: {Recipes:", but that was before narrowing it down to just the above mods and data pack. In case it helps, here is a gist of the Entity Data copied from the log (first with trades working, rest with broken trades): https://gist.github.com/BioMasterZap/251bf17aab961cba70b1115114f148dd

Also, it is worth noting that I have only been able to replicate this problem with the Beekeeper and not with any Villager Professions, vanilla or modded. If other mods that add Professions like Sawmill or Beautify are present, the Carpenter and Botanist, as well as all Vanilla Professions, will be able to trade, just not the Beekeeper. So it seems it is specific to the Beekeeper and not an issue of Crossbow Expansion, GlitchCore, and Villager Trade Rebalance breaking all Villagers or Modded Villagers in general.

Given how obscure and specific this is, I understand if this isn't a priority or even something you want to look into. I spent hours trying to figure out what was going on and am still at a loss for why those specific mods seem to be causing this behavior solely for Beekeepers. So if it isn't something that can be fixed, I am fine with disabling the profession in my Mod Pack but I felt I should report in case it might help you or any other that might run into the same issue.

**Comment by Faboslav** [comment]
Hello, I tested this and its due to trade rebalance datapack, this will not be resolved in any way, if the trade rebalance is released, then fix will be made until it, there is nothing to do :).

**Comment by BioMasterZap** [comment]
Well, it is not solely due to the Trade Rebalance since if you remove Crossbow Expansion or GlitchCore, the Beekeeper works fine with Trade Rebalance enabled. And as mentioned, other modded villager profession still work under the same circumstances that breaks trades for the Beekeeper. But understandable this isn't a priority to fix while the Trade Rebalance is experimental.

**Comment by Faboslav** [comment]
Yeah, it's true, but as you say, with my time availability, debugging something partly related to experimental feature is not what i want to do, ofc if its fully released in some kind of snapshot, i will do the fixing :)., anyway thanks for letting me know, since this info could be really useful in the future. I will close this for now.
