### ISSUE TITLE
Bamboo, cherry, crimson and warped beehives produces general wood sound instead of their own wood sound

### ISSUE THREAD

**Issue by lzm11111111** [Faboslav/friends-and-foes#253]
The bamboo, cherry, crimson and warped beehives produce general wood sound, despite they have their own wood sounds, it's just a small detail and should be easy to fix.

**Comment by Faboslav** [comment]
Yeah, this is true since 1.19.3, will be fixed with next release.

**Comment by Faboslav** [comment]
Should be fixed with 3.0.0 release.
