### ISSUE TITLE
1.21 crashing on startup

### ISSUE THREAD

**Issue by xnite7** [Faboslav/friends-and-foes#255]
### Minecraft version information

1.21

### Mod loader information

Fabric

### Mod loader version information

0.16.4

### Mod version information

2.0.17

### Reproduction Steps

v

### Crash Report and latest.log

[13:45:17] [main/ERROR]: Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Fabric API' (fabric-api) 0.100.7+1.21, mod 'Fabric API' (fabric-api) 0.101.2+1.21 and mod 'Fabric API' (fabric-api) 0.102.0+1.21 with mod 'Fabric API' (fabric-api), version 0.103.0+1.21.1 or later.
More details:
	 - Mod 'Friends&Foes' (friendsandfoes) 2.0.[17] requires version 0.103.0+1.21.1 or later of mod 'Fabric API' (fabric-api), but only the wrong versions are present: 0.102.0+1.21/0.101.2+1.21/0.100.7+1.21!

**Comment by Franco227** [comment]
Can confirm, Friends&Foes 2.0.17 now requires a Fabric API version made for 1.21.1 only, making it unplayable on 1.21.

**Comment by Faboslav** [comment]
I remarked all the versions, so 2.0.16 is now only for 1.21 and 2.0.17 only for 1.21.1, will need to look later, how to make it work on both of these.

**Comment by mpustovoi** [comment]
The Modrinth App constantly wants to update Friends&Foes to Fabric version 1.21.1 on my 1.21 instance.
This is what the page looks like when I manually install v2.0.16, the latest one for Fabric 1.21
![image](https://github.com/user-attachments/assets/63c1c9dd-08ca-4ddc-9758-3c41b2ebcf4b)
This is what it looks like when I 'update' the mod:
![image](https://github.com/user-attachments/assets/4eee068a-ef8c-44bc-915a-e62fa1b39ee7)
If I delete the mod and reinstall it via mods search, I get v1.21-2.0.16, but I can still upgrade to v1.21.1-2.0.17

**Comment by Faboslav** [comment]
I think that there is nothing else i can do now, at least until releasing new version. 2.0.16 is everywhere marked only for 1.21, and 2.0.17 for 1.21.1. Sadly i dont have any other option to do something now, i will try to release the nee version soon, but until then it is what it is :/. If anyone have any idea what to do, i can try that.

**Comment by mpustovoi** [comment]
I already had a similar problem in the Modrinth App with another mod. However, there the author uploaded the 1.21 file for the mod version 1.20.1, which is why the App was confused.
For now, I can just edit the mod file through the archiver so that the Modrinth App doesn't detect it.

**Comment by mpustovoi** [comment]
Perhaps this is some kind of file indexing problem on the part of Modrinth itself. Since there have been constant delays with App v8.X, and I cannot add a new mod to my instance that was updated to this version less than 4 hours ago. Same with updating mods.

**Comment by mpustovoi** [comment]
Fixed, thanks.

**Comment by Faboslav** [comment]
Great! I will try to get it right with the next release :).
