### ISSUE TITLE
Illusioner doesn't drop totem of illusion

### ISSUE THREAD

**Issue by LeafWDM** [Faboslav/friends-and-foes#257]
### Minecraft version information

1.21.1

### Mod loader information

Fabric

### Mod loader version information

0.16.3 (fabric)

### Mod version information

2.0.17

### Expected Behavior

According to the wiki the illusioner should always drop the totem of illusion upon death.

### Actual Behavior

On my fabric server 3 illusioners have been killed and no totems of illusion have dropped.

### Reproduction Steps

1. Find an illusioner shack
2. Kill the illusioner

**Comment by Faboslav** [comment]
Hello there, some other mod is messing with illusioners loot table then.

**Comment by LeafWDM** [comment]
I'm wondering why. Could vanillatweaks' More Mob Heads datapacks be causing it? Or any of its other datapacks that affect loot tables? Perhaps Name tag tweaks which makes mobs drop a name tag if they are named? I can send a full server mod and datapack list if you would like.

**Comment by Faboslav** [comment]
That could help, but some debugging will be still needed, probably enabling and disabling mods/datapacks one by one :/.

**Comment by LeafWDM** [comment]
Just tested, it's definitely more mob heads from vanillatweaks. Any tips on how I could make them compatible? Include both the head and the totem in the loot table?

**Comment by Faboslav** [comment]
I will close this for now, as i cant apply any fix to this.
