### ISSUE TITLE
Wildfire Crown is Unenchantable

### ISSUE THREAD

**Issue by milkev** [Faboslav/friends-and-foes#259]
### Minecraft version information

1.21.1

### Mod loader information

NeoForge

### Mod loader version information

21.1.34

### Mod version information

2.0.17

### Expected Behavior

Can add armour enchantments such as mending, protection, unbreaking, etc to the wildfire helmet

### Actual Behavior

Wildfire Helmet does not support any enchantments

### Reproduction Steps

1. Take Wildfire Helmet
2. Attempt to enchant with books
3. Attempt to enchant with enchanting table
4. Attempt to enchant with commands
5. Everything Fails

### Screenshots & files

![image](https://github.com/user-attachments/assets/a6784363-0aa9-4beb-a577-c0a2f963ff71)

**Comment by Faboslav** [comment]
Yeah, a new tag for enchantable heads was introduced, which is missing from Friends&Foes, thanks for the report, this will be fixed in the new version!

**Comment by Faboslav** [comment]
Should be fixed with 3.0.0 release.
