### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by Hinochi** [Faboslav/friends-and-foes#26]
### Minecraft version information

1.18.2

### Mod loader information

Fabric

### Mod loader version information

0.13.3 (Fabric)

### Mod version information

Friends&Foes mc1.18.2-1.3.3 (Fabric)

### Reproduction Steps

1. Launch Minecraft
2. Select singleplayer
3. Open world
4. World finishes loading
5. Crash

### Crash Report and latest.log

[crash-2022-04-07_22.06.37-server.txt](https://github.com/Faboslav/friends-and-foes/files/8448493/crash-2022-04-07_22.06.37-server.txt)
[latest.log](https://github.com/Faboslav/friends-and-foes/files/8448538/latest.log)

### Additional information

I did add Friends&Foes after playing with Charm and The Bumblezone for a while. If the solution is to make a new world, that's fine.

**Comment by TelepathicGrunt** [comment]
@Hinochi Please update Bumblezone. I already fixed this crash a few days ago with v5.0.9 Bumblezone. This issue report can be closed.
