### ISSUE TITLE
[1.21 NeoForge] Entity Ticking Error

### ISSUE THREAD

**Issue by NovaLynxie** [Faboslav/friends-and-foes#260]
### Minecraft version information

Minecraft 1.21

### Mod loader information

NeoForge

### Mod loader version information

21.0.167 (NeoForge)

### Mod version information

2.0.16

### Reproduction Steps

1. Create new or load existing world
2. Walk around till a Mauler entity loads in
3. Game crashes - Check error log, expect entity ticking error.

### Crash Report and latest.log

Crash Log: [crash-2024-09-16_15.37.45-server.txt](https://github.com/user-attachments/files/17015021/crash-2024-09-16_15.37.45-server.txt)
Latest Log: [latest.log](https://github.com/user-attachments/files/17015033/latest.log)

### Additional information

I confirmed none of these mods are causing the crash; however, the affected mod (Friends & Foes) prevents me from using any of its addons due to the world tick crashing error.

Custom modpack instance mods list:
1.  aggroindicator-1.1.1+neoforge1.21
2.  appleskin-neoforge-mc1.21-3.0.5
3.  armoreddoggo-neoforge-1.21-0.3.0
4.  ArmorStatues-v21.0.1-1.21-NeoForge
5.  athena-neoforge-1.21-4.0.1
6.  BagOfHolding-v21.0.3-1.21-NeoForge
7.  bagus_lib-1.21-12.5.0
8.  bamboodelight-1.0.2.2-1.21
9.  beekeeperhut-neoforge-mc1.21-2.0.1
10.  bettercombat-neoforge-2.0.3+1.21.1
11.  BetterTridents-v21.0.1-1.21-NeoForge
12.  BlockRunner-v21.0.0-1.21-NeoForge
13.  blur-neoforge-5.0.0+1.21
14.  brickfurnace-neoforge-1.21-4.1.1.0
15.  caelus-neoforge-7.0.1+1.21.1
16.  carryon-neoforge-1.21-2.2.1
17.  chipped-neoforge-1.21-4.0.0
18.  cloth-config-15.0.130-neoforge
19.  Clumps-neoforge-1.21-18.0.0.2
20.  collective-1.21.1-7.84
21.  common-networking-neoforge-1.0.16-1.21
22.  Controlling-neoforge-1.21-18.0.4
23.  coroutil-neoforge-1.21.0-1.3.8
24.  corpse-neoforge-1.21.1-1.0.14
25.  curios-neoforge-9.0.10+1.21
26.  DoggyTalentsNext-1.21.1-1.18.30
27.  DTNPaletteOfPaws-1.21-1.2.1
28.  dynamiccrosshair-8.1+1.21-neoforge
29.  EasyAnvils-v21.0.5-1.21-NeoForge
30.  EasyMagic-v21.0.4-1.21-NeoForge
31.  eatinganimation-1.21.0-6.0.1
32.  EchoChest-v21.0.0-1.21-NeoForge
33.  EffectDescriptions-v21.0.1-1.21-NeoForge
34.  emi-1.1.12+1.21+neoforge
35.  endersdelight-1.21-1.0.1
36.  endrem-neoforge-1.21.X-6.0.2
37.  entity_model_features_neoforge_1.21-2.2.6
38.  entity_sound_features_neoforge_1.21-0.4
39.  entity_texture_features_neoforge_1.21-6.2.4
40.  expandeddelight-0.1.2.2
41.  expandedstorage-neoforge-1.21-14.1.2
42.  extradelight-2.0.4
43.  fallingleaves-1.21-2.4.0
44.  FarmersDelight-1.21-1.2.4
45.  Female-Gender-Mod-neoforge-1.21-3.2.2
46.  fishermens_trap-3.0.2
47.  flowerymooblooms-neoforge-mc1.21-2.0.2
48.  friendsandfoes-neoforge-mc1.21-2.0.16
49.  fruitsdelight-1.2.1+1
50.  gml-6.0.1
51.  guardvillagers-2.3.0-1.21
52.  handcrafted-neoforge-1.21-4.0.1
53.  healingcampfire-1.21.1-6.1
54.  Highlighter-1.21-neoforge-1.1.11
55.  Icarus-NeoForge-4.0.0
56.  Iceberg-1.21-neoforge-1.2.5
57.  Jade-1.21-NeoForge-15.1.6
58.  LegendaryTooltips-1.21-neoforge-1.4.11
59.  midnightlib-1.6.3
60.  moonlight-1.21-2.14.18-neoforge
61.  moredelight-24.09.10-1.21-neoforge
62.  nyfsspiders-neoforge-1.21-2.3.1
63.  oceansdelight-neoforge-1.0.3-1.21
64.  player-animation-lib-forge-2.0.0-alpha1+1.21
65.  polymorph-neoforge-1.0.6+1.21.1
66.  polytone-1.21-2.4.15
67.  Prism-1.21-neoforge-1.0.9
68.  PuzzlesLib-v21.0.28-1.21-NeoForge
69.  realcamera-1.21-neoforge-0.6.1-beta
70.  resourcefulconfig-neoforge-1.21-3.0.3
71.  resourcefullib-neoforge-1.21-3.0.10
72.  sawmill-1.21-1.5.3-neoforge
73.  Searchables-neoforge-1.21-1.0.5
74.  ShoulderSurfing-NeoForge-1.21.1-4.4.1
75.  sleeping-bags-neoforge-1.21.1-1.0.8
76.  sound-physics-remastered-neoforge-1.21.1-1.4.6
77.  spyglass_improvements-1.5.7+mc1.21+neoforge
78.  Stoneworks-v21.0.0-1.21-NeoForge
79.  storagedelight-24.09.11-1.21-neoforge
80.  StrawStatues-v21.0.1-1.21-NeoForge
81.  sweetdelight-1.0.3.2-1.21
82.  tofucraft-1.21-11.5.0.3
83.  tofudelight-1.21-4.0.1
84.  travelersbackpack-neoforge-1.21.1-10.1.1
85.  travelerscompass-1.21-3.0.5-neoforge
86.  ubesdelight-neoforge-1.21-0.2.0-beta-2
87.  veinmining-neoforge-5.0.0-beta.2+1.21
88.  VisualWorkbench-v21.0.5-1.21-NeoForge
89.  voicechat-neoforge-1.21.1-2.5.22
90.  warp_book-1.21-3.5.0
91.  watut-neoforge-1.21.0-1.1.4
92.  waveycapes-neoforge-1.4.9-mc1.21
93.  weaponmaster_ydm-neoforge-1.21-4.2.5
94.  Xaeros_Minimap_24.4.0_NeoForge_1.21
95.  XaerosWorldMap_1.39.0_NeoForge_1.21
96.  zmedievalmusic-1.21-2.1

**Comment by Faboslav** [comment]
What kind of server is this?

**Comment by Faboslav** [comment]
Based on the crash log, there is nothing wrong with Friends&Foes, seems like something straight in the NeoForge.

**Comment by Faboslav** [comment]
Should be fixed, with the latest release of the mod mentioned in the last comment :)
