### ISSUE TITLE
Ice chunk spawns by iceologer does not owned by the iceologer, unlike arrow and evoker fangs

### ISSUE THREAD

**Issue by lzm11111111** [Faboslav/friends-and-foes#261]
### Minecraft version information

1.20.1

### Mod loader information

Forge

### Mod loader version information

47.3.0

### Mod version information

Latest

### Expected Behavior

The ice chunks spawns by iceologer should owned by iceologer, like evoker's fangs summon by evokers, when the iceologer's ice chunks kill you, this kill should included in the statistics

### Actual Behavior

The ice chunks spawns by Iceologer does not owned by iceologer, when the iceologer's ice chunk killed you, this kill does not included in the statistics

### Reproduction Steps

1. Spawn an iceologer
2. Get hurt to make the ice chunk can kill you by one hit
3. View the statistics
4. The kill does not included in the statistics

**Comment by Faboslav** [comment]
Hello there, you are absolutely correct, i will fix the damage reference with the next update :).

**Comment by Faboslav** [comment]
Should be fixed with 3.0.0 release.
