### ISSUE TITLE
1.21  when creating a world with experimental functions, trading with beekeepers does not work

### ISSUE THREAD

**Issue by Koksya** [Faboslav/friends-and-foes#262]
### Minecraft version information

1.21

### Mod loader information

Fabric

### Mod loader version information

0.16.4 Fabric

### Mod version information

friendsandfoes-fabric-mc1.21-2.0.16.jar

### Expected Behavior

When creating a world with an experimental feature and installing a hive next to a villager, trade should be available

### Actual Behavior

When creating a world with an experimental function and installing a hive next to a resident, trade is not available, the villager shakes his head

### Reproduction Steps

1. setting up the world
2. Enable the experimental function of trading with villagers
3. create a world
4. place the hive next to the villager
5. villager becomes a beekeeper
6. We try to bargain with him by clicking on him

**Comment by Faboslav** [comment]
Hello there, https://github.com/Faboslav/friends-and-foes/issues/250 is the same issue and until this is not experimental i will probably not look into it

**Comment by Koksya** [comment]
Hello, 

I got acquainted with https://github.com/Faboslav/friends-and-foes/issues/250. I see that GlitchCore is used there. I checked it myself - I also use this mod version 1.21 - 2.0.0.3. Could there be a conflict with these libraries or is it 100% a problem with the experimental function? Is there any advice on how to disable it in the created world, just to be sure?

**Comment by Faboslav** [comment]
I mean i dont know what is the cause, and since its related to the experimental feature, i dont want to spend any time on this, since i do have a lot of other stuff i need to do or debug. What do you mean by "disabling it"?
