### ISSUE TITLE
Request: Reach Potion Item Requirement

### ISSUE THREAD

**Issue by NolanHewitt** [Faboslav/friends-and-foes#263]
Would it be possible to make the reach potions require a tag like c:claw or friendsandfoes:claw instead so that compatibility could be added to other mods which have crab claws in modpacks?
Potion recipes don't seem changeable with datapacks so I can't do anything to change it right now in my modpack : (

**Comment by NolanHewitt** [comment]
Fair enough, I don’t know a ton about how potion recipes work since I’ve only ever worked with datapacks so I didn’t know if it was possible. Thank you for the response!

**Comment by Faboslav** [comment]
No problem, closing this for now :).
