### ISSUE TITLE
Crash when creating a new world

### ISSUE THREAD

**Issue by 12Mosch** [Faboslav/friends-and-foes#264]
### Minecraft version information

1.21.1

### Mod loader information

NeoForge

### Mod loader version information

21.1.61 (NeoForge)

### Mod version information

3.0.0

### Reproduction Steps

1. Start Minecraft
2. Press Singeplayer
3. Without any world mc tries to create a new world **and** the game crashed

### Crash Report and latest.log

[crash-2024-09-26_12.06.10-client.txt](https://github.com/user-attachments/files/17146574/crash-2024-09-26_12.06.10-client.txt)
[latest.log](https://github.com/user-attachments/files/17146624/latest.log)

### Additional information

	- ae2 19.0.23-beta
	- ae2qolrecipes 1.2.0
	- ae2wtlib 19.1.4-beta
		\-- ae2wtlib_api 19.1.4-beta
	- aiimprovements 0.5.3
	- ambientenvironment 18.0.0.1
	- ambientsounds 6.1.2
	- amendments 1.21-1.2.10
	- amplified_nether 1.2.5
	- anvilrestoration 2.3
	- appleskin 3.0.5+mc1.21
	- appmek 1.6.1
	- architectury 13.0.6
	- artifacts 12.0.5
		\-- expandability 12.0.0
	- athena 4.0.1
	- autochefsdelight 2.0.0+neoforge
	- azurelib 2.3.24
	- badoptimizations 2.1.4
	- bagus_lib 1.21.1-13.3.0
	- balm 21.0.19
		\-- kuma_api 21.0.5-SNAPSHOT
	- bigreactors 1.21.1-2.4.9
	- butchercraft 2.6.0
	- caelus 7.0.1+1.21.1
	- car 1.21.1-1.0.28
	- chat_heads 0.13.2
	- cherishedworlds 10.0.2+1.21.1
	- chipped 4.0.1
	- chunky 1.4.16
	- cloth_config 15.0.140
	- clumps 19.0.0.1
	- collective 7.84
	- colorfulhearts 10.3.8
	- comforts 9.0.2+1.21.1
		\-- spectrelib 0.17.2+1.21
	- commonnetworking 1.0.16-1.21
	- controlling 19.0.2
	- cratedelight 24.09.03-1.21-neoforge
	- creativecore 2.12.15
	- creeperoverhaul 4.0.5
	- cucumber 8.0.5
	- curios 9.0.11+1.21
	- deathfinder 21.1.0
	- deeperdarker 1.3.1
	- dungeons_arise 2.1.60
	- dungeons_arise_seven_seas 1.0.3.2
	- durabilitytooltip 1.1.5
	- dyed 1.2.0
	- dynamic_fps 3.7.3
	- easy_piglins 1.21.1-1.0.13
	- easy_villagers 1.21.1-1.1.23
	- elevatorid 1.21.1-1.11.3
	- emi 1.1.13+1.21.1+neoforge
	- emi_enchanting 0.1.2+1.21+neoforge
	- emi_loot 0.7.3+1.21+neoforge
	- enderio 7.0.2-alpha
		|-- endercore 7.0.2-alpha
		|-- enderio_armory 7.0.2-alpha
		|-- enderio_base 7.0.2-alpha
		|-- enderio_conduits 7.0.2-alpha
		|-- enderio_conduits_modded 7.0.2-alpha
		\-- enderio_machines 7.0.2-alpha
	- enderzoology 21.1.2
	- enhanced_attack_indicator 1.1.1+1.21-forge
	- entity_model_features 2.2.6
	- entity_sound_features 0.4
	- entity_texture_features 6.2.5
	- entityculling 1.7.0
	- expandeddelight 0.1.2.2
	- expandedstorage 14.1.5
	- extended_industrialization 1.9.4-beta-1.21.1
	- extradelight 2.0.4
	- farmersdelight 1.2.4
	- ferritecore 7.0.0
	- friendsandfoes 3.0.0
	- fusion 1.1.1+a
	- fzzy_config 0.5.0+1.21+neoforge
	- geckolib 4.6.5
	- geophilic 3.1.3
	- gravestone 1.21.1-1.0.23
	- guideapi_vp 2.3.0
	- handcrafted 4.0.2
	- hideexperimentalwarning 1.2
	- hunters_return 1.21-18.1.0
	- hwg 3.0.1
	- illagerinvasion 21.1.2
		\-- extensibleenums 21.1.1
	- immediatelyfast 1.2.21+1.21.1
	- industrialforegoing 1.21-3.6.13
	- infinitetrading 4.5
	- inventorytotem 3.3
	- iris 1.8.0-beta.4+mc1.21.1
	- irons_spellbooks 1.21-3.5.0
		\-- playeranimator 1.0.2-rc1+1.21
	- jade 15.4.1+neoforge
	- jamlib 1.0.11+1.21
	- jei 19.18.10.218
	- kotlinforforge 5.5.0
	- leavesbegone 21.1.0
	- letmedespawn 1.3.2
	- megacells 4.0.2
	- mekanism 10.7.7
	- mekanismadditions 10.7.7
	- mekanismgenerators 10.7.7
	- mekanismtools 10.7.7
	- merequester 1.21.1-1.1.7
	- midnightlib 1.6.3
	- minecraft 1.21.1
	- modelfix 1.21-1.10
	- modern_industrialization 2.2.24
		\-- grandpower 3.0.0
	- modernfix 5.19.3+mc1.21.1
	- modonomicon 1.106.0
	- moonlight 1.21-2.14.19
	- moredelight 24.09.16-1.21-neoforge
	- mousetweaks 2.26.1
	- mr_edf_remastered 5.0-beta2
	- mr_scorched 1.1.4a
	- mr_serversleep 1-datapack
	- mr_tidal_towns 1.3.3
	- mru 1.0.2+1.21+neoforge
	- mutantmonsters 21.1.0
	- mysticalagradditions 8.0.0
	- mysticalagriculture 8.0.6
	- neoforge 21.1.61
	- noisium 2.3.0+mc1.21-1.21.1
	- notenoughanimations 1.7.6
	- nullscape 1.2.7
	- observable 5.4.3
	- occultism 1.159.5
	- octolib 0.4.2
	- patchouli 1.21-87-NEOFORGE
	- pneumaticcraft 8.1.3
	- polymorph 1.0.6+1.21.1
	- polytone 1.21-2.4.16
	- portfolio 1.21-1.4.1-neoforge
	- powah 6.1.2
	- puzzleslib 21.1.10
	- quarryplus 21.1.103
	- radium 0.13.1+git.4994e83
	- raided 0.1.4.2
	- rechiseled 1.1.6+a
	- reeses_sodium_options 1.8.0-beta.4+mc1.21.1
	- relics 0.9.0.2
	- resourcefulconfig 3.0.4
	- resourcefullib 3.0.10
	- rightclickharvest 4.3.1+1.21
	- searchables 1.0.1
	- securitycraft 1.9.10-beta9
	- servercore 1.5.5+1.21.1
	- shulkerboxtooltip 5.1.1+1.21.1
	- skinlayers3d 1.6.7
	- smartbrainlib 1.16.1
	- smarterfarmers 1.21-2.1.4
	- sodium 0.6.0-beta.2+mc1.21.1
		|-- fabric_api_base 0.4.42+d1308ded19
		|-- fabric_block_view_api_v2 1.0.10+9afaaf8c19
		|-- fabric_renderer_api_v1 3.4.0+acb05a3919
		\-- fabric_rendering_data_attachment_v1 0.3.48+73761d2e19
	- sodiumleafculling 1.0.0
	- sound_physics_remastered 1.21.1-1.4.6
	- sounds 2.1.0+1.21+neoforge
		\-- yet_another_config_lib_v3 3.5.0+1.21-neoforge
	- sparsestructures 2.2.0
	- stoneworks 21.1.0
	- storagedelight 24.09.11-1.21-neoforge
	- storagedrawers 13.4.0
	- supermartijn642configlib 1.1.8
	- supermartijn642corelib 1.1.17+i
	- teamlapenlib 1.10.0-beta.2
		\-- vampirism 1.10.0-beta.2
	- tectonic 2.4.1a
	- terraform 7.0.1
		\-- doapi 1.3.0-beta-release
	- terralith 2.5.5
	- tesseract_api 1.5.3-beta-1.21.1
	- thaumon 2.3.0+1.21
	- the_bumblezone 7.7.1+1.21.1-neoforge
	- titanium 4.0.21
	- tofucraft 1.21.1-12.5.0.1
	- tofudelight 1.21.1-4.2.1
	- toms_storage 2.0.9
	- torchmaster 21.1.0-alpha
	- trade_cycling 1.21.1-1.0.14
	- tradingpost 21.1.0
	- travelersbackpack 10.1.2
	- twilightdelight 3.0.0+4
		\-- l2core 3.0.7+42
	- twilightforest 4.6.2780
	- ubesdelight 0.2.0
	- undergarden 0.8.21
	- vampiresdelight 0.1.9b
	- vegetablesdelight 1.0.5-1.21
	- villagernames 8.1
	- vinery 1.5.0-beta-release
	- waveycapes 1.4.9
	- waystones 21.1.4
	- winterly 0.11.2+1.21
	- xaerominimap 24.4.0
	- xaeroplus 2.24
	- xaeroworldmap 1.39.0
	- zerocore 1.21.1-2.4.9

**Comment by Faboslav** [comment]
I just tested this, i dont get any crash, weird
![Screenshot 2024-09-26 at 12 45 33](https://github.com/user-attachments/assets/7085d510-69b9-490d-9f03-ec01c766f097)

**Comment by Faboslav** [comment]
Can you please try 3.0.1?

**Comment by 12Mosch** [comment]
Now it works. Thanks!

**Comment by Faboslav** [comment]
Great to hear that, thanks for the report! :)
