### ISSUE TITLE
Crash with IndyPets mod 

### ISSUE THREAD

**Issue by S0ullessW0lf404** [Faboslav/friends-and-foes#267]
### Minecraft version information

1.20.1

### Mod loader information

Fabric

### Mod loader version information

0.16.5

### Mod version information

3.0.0

### Reproduction Steps

1.- Have Friends & Foes (3.0.0) and IndyPets (1.4.2 or lesser)
2.- Enter a world with both mods loaded.
3.- Try to put any pets into "independent mode" 

### Crash Report and latest.log

[crash-2024-09-26_13.30.50-server.txt](https://github.com/user-attachments/files/17154140/crash-2024-09-26_13.30.50-server.txt)
[latest.log](https://github.com/user-attachments/files/17154141/latest.log)

### Additional information

Mods used:
**Friends and Foes version "3.0.0" 
IndyPets version"1.4.2"**

The crash is likely to be caused by the "**Glare**" according to the first line of the crash-log, **lowering** the F&F version seems to fix the issue (2.0.17 works fine). doing the same with IndyPets still causes the crash (with F&F 3.0.0).

The crash occurs by **interacting with entities** like dogs and cats, asides from the glare.

**Comment by bafb** [comment]
same
[crash-2024-09-26_15.03.17-server.txt](https://github.com/user-attachments/files/17156146/crash-2024-09-26_15.03.17-server.txt)

**Comment by Faboslav** [comment]
I believe, that indy pets will need to be updated to work with 3.0.0 version, because i did some internal changes, i will create issue on their side.

**Comment by Faboslav** [comment]
This is fixed with the new version of indy pets.

**Comment by S0ullessW0lf404** [comment]
Everything seems to work fine so far with both new versions, thanks!
