### ISSUE TITLE
Incorrect catalogue config factory path causes launch crash

### ISSUE THREAD

**Issue by AgentK20** [Faboslav/friends-and-foes#268]
### Minecraft version information

1.20.1

### Mod loader information

Fabric

### Mod loader version information

0.16.5

### Mod version information

3.0.1

### Reproduction Steps

Launch game using Fabric modloader with Catalogue mod installed, game crashes.

### Crash Report and latest.log

https://mclo.gs/9wys1jV

### Additional information

Wrote a PR to fix it, will reference this issue from PR.

**Comment by AgentK20** [comment]
PR to fix: https://github.com/Faboslav/friends-and-foes/pull/269

**Comment by Faboslav** [comment]
Thanks, will do a release with that :).

**Comment by Faboslav** [comment]
Should be fixed with 3.0.3, thanks!
