### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by Ryuushen** [Faboslav/friends-and-foes#270]
### Minecraft version information

1.20.1

### Mod loader information

Forge

### Mod loader version information

Forge 47.3.10

### Mod version information

3.0.3

### Reproduction Steps

Crashed on startup, only with 3.0.3 version. It works perfectly fine with 2.0.17

### Crash Report and latest.log

[fabric_crash-2024-09-30_09.32.57-client.txt](https://github.com/user-attachments/files/17193550/fabric_crash-2024-09-30_09.32.57-client.txt)
[fabric_latest.log](https://github.com/user-attachments/files/17193551/fabric_latest.log)
[forge_crash-2024-09-30_09.40.19-client.txt](https://github.com/user-attachments/files/17193553/forge_crash-2024-09-30_09.40.19-client.txt)
[forge_latest.log](https://github.com/user-attachments/files/17193554/forge_latest.log)

### Additional information

Firstly, I just want to mention that I'm using [Sinytra Connector](https://www.curseforge.com/minecraft/mc-mods/sinytra-connector). I understand that might be an addition of causing this crash. And I'm fully understand that you might not fix it or support Sinytra but I just want to give it a shot in hope you might take a look at it. 

I included both, Forge and Fabric versions of Friends and Foes logs. Because they give different crash.

Thank you. I love your mods, Have been using it in my modpack with friends since it first release and had no problem til now.

**Comment by Faboslav** [comment]
Why dont you use 1.20.1 version for the forge? https://www.curseforge.com/minecraft/mc-mods/friends-and-foes-forge/files/5767545

**Comment by Faboslav** [comment]
Also if there is a crash with a sinytra connector, then it needs to be fixed on sinytra connector end

**Comment by Ryuushen** [comment]
> Also if there is a crash with a sinytra connector, then it needs to be fixed on sinytra connector end

I tried on both forge and fabric version of the mod. And yeah I thought so too, for now I will just use the older version until they fix it. Thank you

**Comment by Faboslav** [comment]
I will try to do some changes in the mod, and we will see if that helps :).

**Comment by Faboslav** [comment]
I found a solution, will be fixed in the next release :).

**Comment by Faboslav** [comment]
Fix for this error should be out with the 3.0.4 release, its possible that in large modpacks there will be another problem, we will see :).
