### ISSUE TITLE
Buttercup White Texture

### ISSUE THREAD

**Issue by Niconoko** [Faboslav/friends-and-foes#272]
### Minecraft version information

1.21.1

### Mod loader information

NeoForge

### Mod loader version information

21.1.62

### Mod version information

3.0.3

### Expected Behavior

Not expecting extra white texture around the flower?

### Actual Behavior

Appears to be having extra white texture around the flower

### Reproduction Steps

Just load up the game with mods.
Mod list: https://pastebin.com/g9M6yX88
PS. Me also tried to remove all the resource packs, still giving out the same result

### Screenshots & files

![image](https://github.com/user-attachments/assets/37c61e0e-1b18-46f2-bb2e-af89ec1e0824)

**Comment by Faboslav** [comment]
Thanks for the report, this will be fixed in the next release :).

**Comment by Faboslav** [comment]
3.0.4 should be out with the fix.

**Comment by Niconoko** [comment]
Appreciated (´ - ω - ｀)
