### ISSUE TITLE
Тебе стоит изменить сделки с пчеловодом

### ISSUE THREAD

**Issue by SegaBASS08** [Faboslav/friends-and-foes#274]
### Minecraft version information

—

### Mod loader information

Fabric

### Mod loader version information

—

### Mod version information

—

### Expected Behavior

You should change the deals with the beekeeper
I was able to get dozens of stacks of emeralds by selling flowers and bottles while playing with a friend

### Actual Behavior

It is necessary to increase the number of flowers and bottles in the deal. For example, 16 flowers 1 emerald

### Reproduction Steps

—

### Screenshots & files

—

**Comment by Faboslav** [comment]
Trades are already pretty balanced, have you seen other villagers? You can trade 32 sticks for 1 emerald.
