### ISSUE TITLE
Version marked as compatible with 1.19 instead requires 1.19.2

### ISSUE THREAD

**Issue by AlternateMew** [Faboslav/friends-and-foes#276]
### Minecraft version information

1.19

### Mod loader information

Forge

### Mod loader version information

41.1.0 (Forge)

### Mod version information

Forge 41.1.0

### Reproduction Steps

Try to launch game in 1.19

### Crash Report and latest.log

[crash-2024-10-12_10.27.24-fml.txt](https://github.com/user-attachments/files/17350412/crash-2024-10-12_10.27.24-fml.txt)

**Comment by Faboslav** [comment]
Closing this as a lowest supported version for the mod is 1.19.2 not 1.19.
