### ISSUE TITLE
the latest 1.21.1 neoforge version of the mod crashes the server but not the client.

### ISSUE THREAD

**Issue by darock830** [Faboslav/friends-and-foes#278]
### Minecraft version information

1.21.1

### Mod loader information

NeoForge

### Mod loader version information

21.1.65 (neoforge)

### Mod version information

3.0.4

### Reproduction Steps

1. the server previously used 3.0.3 and ran just fine.
2. I deleted the 3.0.3 and replaced it with the 3.0.4 version.
3. the server kept failing to launch.
4. Replacing the mod again with 3.0.3 instead of 3.0.4, I could launch the server without problem.
5. The client does not seem to have the same issue because I can still launch a single player world that also previously used 3.0.3 now updated to 3.0.4.

### Crash Report and latest.log

[crash-2024-10-13_03.55.42-fml.txt](https://github.com/user-attachments/files/17354834/crash-2024-10-13_03.55.42-fml.txt)

**Comment by Faboslav** [comment]
Thanks for the report, i messed up some internal things, this will be fixed asap with 3.0.5
