### ISSUE TITLE
Better Illagers Iceologer Issue

### ISSUE THREAD

**Issue by QwertRvg** [Faboslav/friends-and-foes#281]
### Minecraft version information

1.20.1

### Mod loader information

Fabric

### Mod loader version information

0.16.5

### Mod version information

3.0.3

### Expected Behavior

For the Iceologer to look normal / as intended.

### Actual Behavior

The Iceologer looks very very weird when the Better Illagers resource pack is used. Because the Iceologer borrows visuals from another Illager, I think.

### Reproduction Steps

1. Download Friends and Foes
2. Download and use Better Illagers
3. Spawn an Iceologer
4. look at it

### Screenshots & files

![image](https://github.com/user-attachments/assets/8aef98d2-7107-4cf2-8776-6ab0bbb79646)

**Comment by Faboslav** [comment]
If it works without the Better Illagers resource pack, then it needs to be fixed on the resource pack side, not mine, as this is fully custom mob not a vanilla one.

**Comment by QwertRvg** [comment]
alright, thanks. then i will contact the RP maker
also sorry about the duplicate haha

**Comment by QwertRvg** [comment]
![image](https://github.com/user-attachments/assets/27246ecf-8445-435f-accf-887c3a74509d)

**Comment by SebSemos** [comment]
Some people have reported this issue on my Freshly modded pack.
Iceologer used to have his own model, now it use the vanilla evoker one. 
Not sure what update messed it up. I'll check this later this week.

![2024-10-26_04 12 20](https://github.com/user-attachments/assets/6cc24d4f-ba73-452f-a26f-6497b6d9090e)

**Comment by Faboslav** [comment]
@SebSemos Thanks for looking into it, i think that model was switched some time ago, due to having more compatibility with other things by default, for example with the fresh animations.

**Comment by SebSemos** [comment]
It's been changed on 3.0
I get why you did it, by I'm not a fan of this change. I do believe each entity should have her own model. 
The better illager issue being the prime example of why. 

About fresh animation the evoker don't have second head layer so, the iceologer is missing the hood :/
![2024-10-26_21 52 47](https://github.com/user-attachments/assets/822234db-e1b6-4499-bcb2-f53f67ff6c57)

I hope you'll get back to the iceologer model...

**Comment by Faboslav** [comment]
I went over this again and i cant find the change, i checked the 2.0.15 version and iceologer already uses the evoker layer.

**Comment by Faboslav** [comment]
Fixed with the latest release :).
