### ISSUE TITLE
Inconsistent potion durations

### ISSUE THREAD

**Issue by lantzel0t** [Faboslav/friends-and-foes#283]
### Minecraft version information

1.20.1

### Mod loader information

Fabric

### Mod loader version information

0.16.5

### Mod version information

3.0.5

### Expected Behavior

Potions of reach have inconsistent timings. A basic potion has a duration of a full hour, extending it makes it a whopping two hours, but making the effect stronger kills the duration down to a more normal 1 minute and 30 seconds.

### Actual Behavior

My proposal is for potions to have durations more in line with vanilla, with 3 minutes for a basic potion, and 8 for the extended. 1:30 for a +2 block reach seems right.

### Reproduction Steps

Bug visible in creative menu.

**Comment by Faboslav** [comment]
Having reach for 3/8 mins would be really useless, i know that the durations are not not exactly the vanilla ones, but having an equippable claw item to the hand seemed worse for me.

**Comment by Faboslav** [comment]
Corrected with the latest release :).
