### ISSUE TITLE
mod crashing because of compatibility java_17 ? 

### ISSUE THREAD

**Issue by meepitycrows** [Faboslav/friends-and-foes#284]
### Minecraft version information

1.20.1

### Mod loader information

Fabric

### Mod loader version information

0.16.6 (Fabric)

### Mod version information

3.0.5

### Reproduction Steps

1. Download friends and foes 3.0.0
2. start the server
3. works normally
4. after a few hours it crashes
5. server wont start again 

### Crash Report and latest.log

latest log: https://mclo.gs/CiLEfe5

### Additional information

im using aternos and its a cracked server ive had no issue with this since the start of October but now this happens?? its so odd too that it randomly crashed cause the last few days it worked no issue even hours bfore the server crashed pls help

**Comment by Reinvigorate-4** [comment]
### Minecraft version information
1.21

### Mod loader information
Fabric

### Mod loader version information
0.16.6 (Fabric)

### Mod version information
3.0.5

### Reproduction Steps
1. Start Server
2. Crash on startup

### Crash Report and latest.log
latest log: https://mclo.gs/HMOJTiP

### Additional information
Same issue here, also using an Aternos Server, not cracked though. Never crashed while the server was running but now crashes every time on startup.

**Comment by Faboslav** [comment]
Can you try without carryon and/or axiom? Anyway this feels like problem with the `Aternos` server, sadly there is nothing useful in the log for me, i can try to look into it anyway, but i cant promise anything.
