### ISSUE TITLE
Сarpet Incompatibility

### ISSUE THREAD

**Issue by rtgxjzgsryksryydtyrkry** [Faboslav/friends-and-foes#287]
### Minecraft version information

1.21.1

### Mod loader information

Fabric

### Mod loader version information

Fabric Loader 0.16.9

### Mod version information

3.0.5

### Expected Behavior

Completing a command without a critical failure)

### Actual Behavior

Profiler tick ended before path was fully popped (remainder: 'root.tick.levels.ServerLevel[New World] minecraft:overworld.tick.chunkSource.chunks.pollingChunks.spawnAndTick.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2.thunder2'). Mismatched push/pop?

### Reproduction Steps

FNF, Carpet, Fabric API
New world
/perf start

### Screenshots & files

This error does not allow you to track which mods and datapacks take up performance, which makes optimizing the server much more difficult.

**Comment by rtgxjzgsryksryydtyrkry** [comment]
[2024-11-06-7.log](https://github.com/user-attachments/files/17651626/2024-11-06-7.log)

**Comment by Faboslav** [comment]
Just tried this
![image](https://github.com/user-attachments/assets/80255102-a099-45a1-9810-f6024d22d24c)

**Comment by rtgxjzgsryksryydtyrkry** [comment]
![test](https://github.com/user-attachments/assets/67082a68-6430-420b-a957-97739705af63)

**Comment by rtgxjzgsryksryydtyrkry** [comment]
[2024-11-14_17_26_55-New World-1_21_1.zip](https://github.com/user-attachments/files/17750005/2024-11-14_17_26_55-New.World-1_21_1.zip)

**Comment by rtgxjzgsryksryydtyrkry** [comment]
![45132541](https://github.com/user-attachments/assets/96415bf4-9a76-455e-a4f5-612bebca75ee)

**Comment by Faboslav** [comment]
I found the problem, will be fixed with the next update, thanks! :).

**Comment by Faboslav** [comment]
Fixed with the latest release :).
