### ISSUE TITLE
Friends and foes causes aether fabric port dungeons to not lock/unlock correctly

### ISSUE THREAD

**Issue by AnukWarrior** [Faboslav/friends-and-foes#290]
### Minecraft version information

1.21.1

### Mod loader information

Fabric

### Mod loader version information

0.16.9

### Mod version information

3.0.5

### Expected Behavior

with both aether fabric and friends and foes installed the expected behavior is to be able to fight aether bosses and have dungeons lock and unlock correctly

### Actual Behavior

with friends and foes installed alongside the brand new fabric port of the aether dungeons will not lock/unlock correctly meaning killing a aether boss will not open up the room for the stone chest along side the dungeon blocks remaining locked making them unbreakable when you beat a boss in the aether in survival along side the boss room doors not opening/closing

### Reproduction Steps

1 install aether fabric and friends and foes with dependancys on 1.21.1
2 enter the aether and find a dungeon
3 kill boss of said dungeon
4 dungeon rooms do not lock/unlock correctly

### Screenshots & files

there is also a report over on the aether github Blodhgarm thinks both of you may need to work together on figureing this out as its a rather confusing issue

https://github.com/The-Aether-Team/The-Aether/issues/2354

**Comment by Dragon-Seeker** [comment]
I have an assumption it's down to this mixin that is maybe conflicting with aethers EntityStructureProcessor

**Comment by Dragon-Seeker** [comment]
@AnukWarrior Funny fix is to install [yungs API](https://modrinth.com/mod/yungs-api) mod as it has a [correct mixin](https://github.com/YUNG-GANG/YUNGs-API/blob/1.20/Fabric/src/main/java/com/yungnickyoung/minecraft/yungsapi/mixin/EntityProcessorMixin.java#L3) for this that allows for aether code to work. Friends and foes defers to Yungs API for handling structure entity processing when loaded.

**Comment by Faboslav** [comment]
Hello there, so if the aethers StructureEntityProcessor works along with the yungs api, i can just look at it and do it the same on my side right? The only thing is, i cant find it.

**Comment by Dragon-Seeker** [comment]
@Faboslav Mixin in question from yungs: https://github.com/YUNG-GANG/YUNGs-API/blob/79da28956171c765ce1f035cf3cfad234b41a863/Fabric/src/main/java/com/yungnickyoung/minecraft/yungsapi/mixin/EntityProcessorMixin.java#L78

**Comment by Faboslav** [comment]
@Dragon-Seeker Yeah, i see that yung updated the api, so its compatible with others too, i updated my part of the code too and this should be hopefully fixed with the next release :).
