### ISSUE TITLE
[Suggestions]Add configuration to define how many MAX_ILLUSIONS_COUNT can a illusioner spawn

### ISSUE THREAD

**Issue by shallow-zzt** [Faboslav/friends-and-foes#293]
I want to keep the illusioner spawn. But I think the ability of the illusioner is too overpowered and causes lags.
Illusioners create too many illusions and this causes lags. Also, the ablilty might be too overpowered for some modpacks.

**Comment by Faboslav** [comment]
Hello, i highly doubt that it causes lag, but i can add this as a configuration for sure :).

**Comment by Faboslav** [comment]
Settings are included in the latest release
