### ISSUE TITLE
cant get mobs to spawn naturally 

### ISSUE THREAD

**Issue by gamzzie** [Faboslav/friends-and-foes#32]
![serverimage](https://user-images.githubusercontent.com/105760224/168937856-8f7b1218-b54f-4877-864b-623e1aa97dd0.png)
hi i have a sever open with the friends and foes mod and i cant get the mobs to spawn, it works for single player. i host on server.pro and it get this message when checking the console

**Comment by Faboslav** [comment]
Hello this Is not an error, You can build the copper golem, illusioner/iceologer can be found in raids and specific structures and if you want to encounter glare or moobloom you just have to explore specific biomes.

As this is not even correctly created issue with needed info, i am closing it.
