### ISSUE TITLE
Minecraft Launcher crash instantly

### ISSUE THREAD

**Issue by wizard54** [Faboslav/friends-and-foes#34]
### Minecraft version information

1.18.2

### Mod loader information

Forge

### Mod loader version information

40.1.21

### Mod version information

1.4.1

### Reproduction Steps

Hello, 
On windows or mac when the jar file is placed in the mod folder, i run the minecraft launcher ( official one not cracked ) and click on launch game 

It instantly crash and raise the error : Code 1 

I know that this is not so much info, but it has been encountered by all the friends with who i am playing, there is no more error messages and any crash report as the game is not launching at all

By any chance if it could help other people facing this issue 

Thanks by advance for your time 
Best Regards

### Crash Report and latest.log

/

**Comment by PhoenixKnight3** [comment]
Do you have architectury installed?

**Comment by Faboslav** [comment]
Hello, i tested it, in my case on osx, with versions bellow, all is working as expected.
![Screenshot 2022-05-30 at 6 53 37](https://user-images.githubusercontent.com/14179066/170919494-1d47a1a7-1021-4a2e-8a22-c0848b58a531.png)
I can not do anything more, if you do not provide crash report or list of other used mods as it is just possible, that there is some kind of incompability, but then again a would need a crash report.

**Comment by Faboslav** [comment]
If the problem persists, even with correct modloader and all dependencies, please open another issue with more context, without more context i am unable to do anything :).
