### ISSUE TITLE
Bee and Beekeeper crash 

### ISSUE THREAD

**Issue by deadlymango** [Faboslav/friends-and-foes#39]
### Minecraft version information

1.18.2

### Mod loader information

Forge

### Mod loader version information

Forge 40.1.51

### Mod version information

friendsandfoes-forge-mc1.18.2-1.4.2.jar

### Reproduction Steps

1. Summon a mob from another mod (Grimoire of Gaia),
2. Fight it.
3. Crash

As you can see, unfortunately, I do not believe that I was performing any action that would be related to the mod at the moment it crashed. There must have been a village nearby with the beekeeper.

I do recall spamming right-click at the time the server crashed, but it is hard to say if that makes any difference. 

This was a fresh world, so I did not do anything to mess with villagers or beekeepers.

### Crash Report and latest.log

[latest.log](https://github.com/Faboslav/friends-and-foes/files/8896919/latest.log)
[crash-2022-06-13_22.38.34-server.txt](https://github.com/Faboslav/friends-and-foes/files/8896923/crash-2022-06-13_22.38.34-server.txt)

### Additional information

#15 is related, but is for Minecraft version 1.18.1. This report is for 1.18.2.

**Comment by Faboslav** [comment]
Hello, i will try to debug and fix this, but pleas update the mod version to 1.4.3.

**Comment by twixstix** [comment]
Just to confirm, this does happen on version 1.4.3 Fabric as well.

**Comment by Faboslav** [comment]
Yes, i believe i do have a solution for that, first fix try to release fix sometime today :).

**Comment by Faboslav** [comment]
So fixed are in place and i shall (hopefully) release the new version today, sorry for the delay :).

**Comment by Faboslav** [comment]
https://github.com/Faboslav/friends-and-foes/releases/tag/mc1.18.2-1.4.4, if there is any problem please let me know.

**Comment by watchout-mods** [comment]
@Faboslav I ran into this on 1.18.1 preventing me to log into the world at all and decided to try applying 897a32649d6e6d680ee8618a7a9bef60e3b56666 - and it seems to have worked - feel free to use this or not.

PS: I think this actually happened because I removed a beehive, with the fix the villager does not revert its profession and keeps walking to the now empty spot where the beehive was previously, staring at empty air...

**Comment by Faboslav** [comment]
@watchout-mods You applied https://github.com/Faboslav/friends-and-foes/commit/897a32649d6e6d680ee8618a7a9bef60e3b56666 for 1.18.1 version, or what do you mean by that?

```
PS: I think this actually happened because I removed a beehive, with the fix the villager does not revert its profession and keeps walking to the now empty spot where the beehive was previously, staring at empty air...
```

Yeah this should be prevented with the next release.

**Comment by watchout-mods** [comment]
> @watchout-mods You applied [897a326](https://github.com/Faboslav/friends-and-foes/commit/897a32649d6e6d680ee8618a7a9bef60e3b56666) for 1.18.1 version, or what do you mean by that?

Yes, works just fine, thanks for making it open source :)
