### ISSUE TITLE
The Wildfire, a Mob that you *want* to encounter during speedruns!

### ISSUE THREAD

**Issue by Caha1an** [Faboslav/friends-and-foes#40]
_This is a feature pitch for when the Wildfire mob gets added to the mod._

Have you ever wondered if there was a way to make blaze rod grinding not suck?
Want to add a bit of spice to a speedrun in case your blaze rod rates happen to also suck?

The Wildfire is the mob for you!

If you happen to slay enough Blazes in the Nether, a Wildfire will appear at the latest slain Blaze with a fancy spawn animation.
This is to prevent players from getting reality checked by the Wildfire too quickly. ;)
Very rarely, a Wildfire will naturally spawn in Nether Fortresses.

If you manage to defeat a Wildfire, you're _**guaranteed at least 4 Blaze Rod Drops**_ for your troubles, up to 8 via looting.
There are also rumors that the shields that the Wildfire uses can be acquired upon victory if at least one shield remains.
If true, the shields could inflict fire damage upon attacking mobs or opposing players and are repaired with magma cream.

The Wildfire's features from Minecraft Dungeons also make their debut in Minecraft in this wonderful "What if...?" mod.

**_Other fun tidbits about the Wildfire_**

- Snowballs inflict increased damage to the Wildfire's shields, even if the player uses the Wildfire Shield to block a snowball.
- The Wildfire Shield burns arrows upon contact and does more damage to wooden tools.
- The "fire aspect" of the Wildfire Shield only applies to physical attacks; does not work underwater.
- Has a dedicated "Boss Health Bar", mainly due to the fight acting like a raid.

**_Specific Spawn Mechanics Pitch via repeat slaying of Blazes:_**

- Base rate of less than 1% chance upon slaying a blaze.
- After slaying 5, the rate increases to 5%.
- After slaying 10 blazes, the rate increases to 25%.
- Once you slay 20 blazes and the wildfire still hasn't spawned, the chances of a Wildfire spawning cap at 50%.
- If by astronomical luck a Wildfire hasn't spawned by that point, you get a guaranteed appearance at Blaze No.30.
(_congrats, now run_)

Only one Wildfire can spawn via this method at a time, Blazes summoned by the Wildfire do not count toward the spawn rate.

**Comment by Faboslav** [comment]
Hello, first of all, thank your for this very detailed suggestion.

The wildfire is already in work and current state and plan for wildfire in short points:
- custom structure in nether like ocean monument with one wildfire in the central(main) room of it
- there will be no boss bar as this will be more like a mini boss (like an elder guardian)
- will probably drop blaze rods and probably special shield (which will work like turtle helmet, but shield, also with one special effect that i am not sure on yet)
- behaviour basically like in mc dungeons, but little bit improved
