### ISSUE TITLE
Waxxing copper

### ISSUE THREAD

**Issue by shadins** [Faboslav/friends-and-foes#41]
### Minecraft version information

1.18.2

### Mod loader information

Fabric

### Mod loader version information

0.14.8

### Mod version information

1.4.4

### Expected Behavior

Clicking on an unwaxed copper block with a honeycomb to wax copper.

### Actual Behavior

When Clicking I am not seeing any particles nor my hand swinging to show an interaction with the copper block and honeycomb. After trying a couple of times, picked up the copper block and it is confirmed not waxed. I am using a couple of other mods in my world but I had tested each and every mod to find which one is causing this issue and found it to be this mod causing this problem.

### Reproduction Steps

place the copper block in the world
right-click copper block with honeycomb in hand
observe the copper block does not become waxed

**Comment by Faboslav** [comment]
Hello, i can confirm, that this is happening, fix will be released today. Thanks :)

**Comment by Faboslav** [comment]
https://github.com/Faboslav/friends-and-foes/releases/tag/mc1.18.2-1.4.5, please let me know if anything else is wrong :).
