### ISSUE TITLE
Incompatibility with Architectury API (Fabric/Forge)

### ISSUE THREAD

**Issue by lindenkron** [Faboslav/friends-and-foes#42]
### Minecraft version information

1.19

### Mod loader information

Fabric

### Mod loader version information

0.14.8

### Mod version information

friendsandfoes-fabric-mc1.19-rc1-1.5.0

### Reproduction Steps

Have architectury-5.7.27-fabric & friendsandfoes-fabric-mc1.19-rc1-1.5.0 installed.

### Crash Report and latest.log

[crash-2022-06-22_02.58.46-client.txt](https://github.com/Faboslav/friends-and-foes/files/8953636/crash-2022-06-22_02.58.46-client.txt)

**Comment by Faboslav** [comment]
Please use new version of the mod and let me know if the problem persists.
