### ISSUE TITLE
error code 1

### ISSUE THREAD

**Issue by RyanReynoldsIsHot** [Faboslav/friends-and-foes#46]
### Minecraft version information

1.18.2

### Mod loader information

Forge

### Mod loader version information

40.1.0

### Mod version information

1.4.5

### Reproduction Steps

I just try to launch minecraft but then it kicks me back in the launcher and tells me that i have invalid java runtime. I've had the same issue on different versions of minecraft and with different versions of mod. I would still like to use this mod so if you know what i should do please share.

### Crash Report and latest.log

[crash-2022-07-08_09.03.57-fml.txt](https://github.com/Faboslav/friends-and-foes/files/9073278/crash-2022-07-08_09.03.57-fml.txt)

**Comment by Faboslav** [comment]
Hello this is error Is not related to Friends&Foes mod in any way:

`Failure` message: Mod adchimneys requires forgeendertech 9.0.0.0 or above
		Currently, forgeendertech is not installed`

You need to install forgeendertech mod of version 9.0.0.0 or newer.

**Comment by Faboslav** [comment]
Is it exactly the same error? Also if you want to get some more help, we can talk about that on discord,  as this is not an issue of Friends&Foes.

**Comment by CarsonIsDumb** [comment]
im having the same problem even after installing forgeendertech

**Comment by Faboslav** [comment]
@CarsonIsDumb Please open the new issue with all related stuff.
