### ISSUE TITLE
Raid Mixin Misinterpreted Logic

### ISSUE THREAD

**Issue by GToidZ** [Faboslav/friends-and-foes#55]
This code checks if the raider is an instance of Iceologer or Illusioner and determines if the entries in config are `false` or not.
However, it is checking for all those entries to be `false`.

Per the `&&` operator in each inner conditionals.
https://github.com/Faboslav/friends-and-foes/blob/5e74121a55c3e5dc2efff42d411a3dd83de014c6/common/src/main/java/com/faboslav/friendsandfoes/mixin/RaidMixin.java#L25-L37

I think the intended behavior should be checking whether any config entry is `false`.
Below is what I think it is intended.
```java
if (
        raider instanceof IllusionerEntity 
        && (
                FriendsAndFoes.getConfig().enableIllusioner == false ||
                FriendsAndFoes.getConfig().enableIllusionerInRaids == false
        )
)
```

**Comment by Faboslav** [comment]
Hello, you are right, that is for sure not intended, i will fix this with the next release (1.5.6).
Also you are probably the first person going through the code and reporting some bad behaviour, so thank you for this :).

**Comment by GToidZ** [comment]
No problem, I was just suspecting after making a raid farm and tweaking the mod's config, haha.
More importantly, cheers to you for making this amazing mod! 🎉

**Comment by Faboslav** [comment]
I am sorry, that this is taking this long, my scope for the update is pretty huge opposite what i had in my mind initially.
