### ISSUE TITLE
Failed Goals

### ISSUE THREAD

**Issue by Robongio** [Faboslav/friends-and-foes#59]
### Minecraft version information

1.19.2

### Mod loader information

Forge

### Mod loader version information

43.1.3 (Forge)

### Mod version information

1.5.7

### Reproduction Steps

The game shuts down a few seconds after loading the terrain.

### Crash Report and latest.log

The game crashed whilst ticking entity
Error: java.lang.IllegalAccessError: failed to access class net.minecraft.world.entity.animal.Bee$BeePollinateGoal from class com.faboslav.friendsandfoes.entity.ai.goal.BeePollinateMoobloomGoal (net.minecraft.world.entity.animal.Bee$BeePollinateGoal is in module minecraft@1.19.2 of loader 'TRANSFORMER' @79d82f66; com.faboslav.friendsandfoes.entity.ai.goal.BeePollinateMoobloomGoal is in module friendsandfoes@1.5.7 of loader 'TRANSFORMER' @79d82f66)

**Comment by fr4nc15c0-15** [comment]
i have the same issue.

**Comment by Faboslav** [comment]
Hello, thank you for the report, i will try to fix ASAP.

**Comment by Faboslav** [comment]
This is hopefully fixed with the 1.5.8 release, please download the newer version of the mod and let me know if everything is okay :).

**Comment by Faboslav** [comment]
https://www.curseforge.com/minecraft/mc-mods/friends-and-foes-forge/files/3956145
