### ISSUE TITLE
Option for turning on/off Glare's glow berries shaking AI

### ISSUE THREAD

**Issue by RedBeast1959** [Faboslav/friends-and-foes#62]
friendsandfoes-forge-mc1.19.2-1.5.10.jar

I hope there's an option for Glare to turn off shaking down glow berries.

Glare will eat up every berries in lush caves and make whole place dark. That behavior contradicts the purpose of finding spot that's dark enough to mob spawn.

Also I really want to release tamed or captured Glare into artifical undergound lush garden with glow berries intact.

**Comment by Faboslav** [comment]
I am currently on the vacation, but i can try to do something like that in the next release :).

**Comment by Faboslav** [comment]
So i implemeted this. Check the 1.5.11 release of the mod please.
