### ISSUE TITLE
Request: Vanilla Illusioner config

### ISSUE THREAD

**Issue by Swagboi7** [Faboslav/friends-and-foes#65]
While the Illusioner with this mod is a pretty good adaptation of the one in Dungeons, I'd love to see a config that reverts the behavior to the vanilla one

(EDIT): Wrote this before realizing it wasn't currently possible. Hoping it's planned to make that change.

**Comment by Faboslav** [comment]
Hello, i will try to come up with something, we will see :)

**Comment by Faboslav** [comment]
So i did what i could for now(with given time), "vanilla" illusioner is basically illager skeleton when disabled, but he doesnt use spells, that will be hopefully fixed in the next releases.
