### ISSUE TITLE
Iceologer and Illusioner in raids unable to disable

### ISSUE THREAD

**Issue by Mahadbaloch** [Faboslav/friends-and-foes#66]
I set appear in raid option in config menu to false but they both still appear in raids.
1.19 fabric

**Comment by Faboslav** [comment]
Hello, i am glad for the report, but fill the proper report here https://github.com/Faboslav/friends-and-foes/issues/new?assignees=Faboslav&labels=bug&template=bug_report.yml, with this you give me literally zero information.
