### ISSUE TITLE
Cannot prevent iceologer and illusioner from appearing in raids

### ISSUE THREAD

**Issue by Mahadbaloch** [Faboslav/friends-and-foes#67]
### Minecraft version information

1.19

### Mod loader information

Fabric

### Mod loader version information

0.14.8

### Mod version information

1.5.5

### Expected Behavior

Turned off appear in raids option and enable spawn option for both mobs.

### Actual Behavior

Both mobs spawn in raids as well as their own structures

### Reproduction Steps

1. Turn off enable in raids and enable spawn toggle from mod menu.
2. Restart game
3. Kill an illager captain
4. Start a new raid
5. Mobs still appear after a few waves

**Comment by Faboslav** [comment]
Hello, i think i fixed this problem in the 1.19 versions of the mod, is this a big problem? I mean if possible i would like to not backport things anymore. Sadly, I dont have much time right now. And i would rather focus on the 1.19 versions.

**Comment by Mahadbaloch** [comment]
It does not seem to work no matter what I do. Fix it if you are free no pressure

**Comment by Faboslav** [comment]
Oh sorry, i miss readed the info, then i will try to fix this, no worries :).

**Comment by Mahadbaloch** [comment]
Wait Wait. I did not realize I was not on the latest version. You can see I am on 1.5.5 not 1.5.10. The newest version is working just fine. Sorry for annoying you with this

**Comment by Faboslav** [comment]
Oh, then i miss read the information twice :D, i am happy that it is working :). I am closing this.
