### ISSUE TITLE
Add the “Rascal” mob (MCL2022)

### ISSUE THREAD

**Issue by arichorn** [Faboslav/friends-and-foes#68]
Hello! Since there’s another mob vote in Minecraft Live 2022 I decided that Rascal can join early.
Hear me out, I know it hasn’t been picked but I do bet that it is not gonna win
![4EFFF792-1306-4077-BFBB-09C93EB80FFD](https://user-images.githubusercontent.com/78001398/194193766-3776e1ad-6fcf-46d0-ab45-ff0feb795e04.jpeg)
This user did a small vote as a test and I can see that the mob Rascal has a definite chance of losing so I hope I letted you know!

**Comment by Faboslav** [comment]
Yeah, it is planned, but lets still wait for the official results :), also Wildfire will be finished with priority, as it is already worked on.

**Comment by Faboslav** [comment]
I am closing this, as this will be worked on later on.

**Comment by arichorn** [comment]
Alright

**Comment by arichorn** [comment]
I predicted the win, knew the Rascal and Tuff Golem would’ve lose.
