### ISSUE TITLE
Small typo in wiki

### ISSUE THREAD

**Issue by Riteo** [Faboslav/friends-and-foes#72]
Sorry to bother you, but I noticed that in the copper button wiki the table lists twice "Waxed Weathered Copper Button", specifically in the row labelled "Oxidized Copper Button or Waxed Weathered Copper Button". I think you meant "Oxidized Copper Button or Waxed **Oxidized** Copper Button".

If that isn't the case, sorry, feel free to close this issue.

**Comment by Faboslav** [comment]
Hello, yes it was a typo, thank you, it is already fixed :).
