### ISSUE TITLE
Wildfire crashes game when in Water

### ISSUE THREAD

**Issue by Bluthirn** [Faboslav/friends-and-foes#76]
### Minecraft version information

1.19.2

### Mod loader information

Forge

### Mod loader version information

Forge 43.1.1 and Forge 43.1.52

### Mod version information

 Friends&Foes mc1.19.2-1.6.0 (Forge)

### Expected Behavior

When the Wildfire takes damage from a watersource it should not crash the game.

### Actual Behavior

The Wildfire crashes the Game when it takes damage from a watersource. 

### Reproduction Steps

1. Spawn a Wildfire in a Watersource. Only testet in the Overworld.
2. It will take 1-3 times Damage, then crash the game.

**Comment by Faboslav** [comment]
Should be fixed with 1.6.1 release, let me know, if there is any other problem please :).
