### ISSUE TITLE
BetterF3's mod overlay doesn't display

### ISSUE THREAD

**Issue by dirtyfargo** [Faboslav/friends-and-foes#79]
### Minecraft version information

1.19.2

### Mod loader information

Forge

### Mod loader version information

43.1.57

### Mod version information

1.6.1

### Expected Behavior

Better F3 mod's debug overlay to display when pressing F3 key.

### Actual Behavior

See attached screenshot
It is also discussed here [github.com/cominixo/BetterF3/issues/84](https://github.com/cominixo/BetterF3/issues/84)

### Reproduction Steps

Run an instance with these 3 mods included:

Better F3
Cloth Config API (Better F3 dependency)
Friends and Foes

Load into world, press F3 key.

### Screenshots & files

![2022-11-29_21 10 02](https://user-images.githubusercontent.com/10457528/204712824-a55dc596-8745-4035-b46c-5edefbdc9042.png)

**Comment by dirtyfargo** [comment]
[Potentially relevant snippet from debug.log](https://gist.github.com/dirtyfargo/494ea1bfb191ca80f8f76c539443d562)

**Comment by Faboslav** [comment]
Hello, I can confirm that this is happening, but in the log, there is not even a mention of friends&foes mod(it does not go trough my code), so this will probably be the compatibility issue on the better f3 mod side.

**Comment by Faboslav** [comment]
As mentioned here https://github.com/cominixo/BetterF3/issues/84#issuecomment-1334753033, i am closing this issue, as there is nothing wrong on my side (adding custom spawn group is totally normal thing to do).
