### ISSUE TITLE
Feature Request - Villager (Guard or Militia)

### ISSUE THREAD

**Issue by RotokEralil** [Faboslav/friends-and-foes#8]
Hello! I love your mod so far!!!
I see you have a beekeeper villager; is it possible to see your take on a town guard or militia? (I havent seen one for Fabric yet).
Thanks again for this mod!
**Is your feature request related to a problem? Please describe.**
None.

**Describe the solution you'd like**
N/A

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Faboslav** [comment]
Hello, thanks for your kind words!

Currently something like town guard or militia is pretty far out of the scope of this mod.
But sometime in the future i would like to create my second mod with focus on revamping the villages and related lore.

**Comment by RotokEralil** [comment]
Thanks for the response! (will keep an eye out for more mods from you :) )
