### ISSUE TITLE
server crash when updated to 1.6.2

### ISSUE THREAD

**Issue by 3dguru** [Faboslav/friends-and-foes#80]
### Minecraft version information

1.19.2

### Mod loader information

Fabric

### Mod loader version information

0.14.10

### Mod version information

1.6.2

### Reproduction Steps

updated mod but mod causes server to crash 

### Crash Report and latest.log

https://pastebin.com/Ja1GbEDP

**Comment by ssamjh** [comment]
👍

**Comment by Faboslav** [comment]
I am on it.

**Comment by Faboslav** [comment]
Should be fixed(and soon released) with https://github.com/Faboslav/friends-and-foes/releases/tag/mc1.19.2-1.6.3.
