### ISSUE TITLE
[Request] Config option to disable beehive variants

### ISSUE THREAD

**Issue by Null-151** [Faboslav/friends-and-foes#81]
### Minecraft version information

1.19.2

### Mod loader information

Forge

### Mod loader version information

43.2.0

### Mod version information

1.6.3

### Expected Behavior

Would be nice to have a config option to disable them since pretty much everything else has a toggle, you end with lots of duplicates if you're running Everycompat/Woodworks

### Actual Behavior

Yeah

### Reproduction Steps

1.Install
2.Check config
3. :(

**Comment by Faboslav** [comment]
Hello, that would be pretty complicated, and i dont want to do toggle for every one block/item/feature of my mod. Also it would ruin the beekeeper villager, as the custom beehives will not work without any additional work on compatibility.

I see that "Everycompat" does not add any beehives. On the other hand "Woodworks" does, but only for basic wood types.

**Comment by Null-151** [comment]
Everycompat does generate beehives for all modded wood types if Woodworks is present, but yeah I totally understand if this is a low priority right now

**Comment by Faboslav** [comment]
If i do anything like this, it would be after i have implemented all the mobs, as it is just more like nice to have feature. I am closing this for now, thank you for your time anyway :).
