### ISSUE TITLE
Alternate lightning rods not working

### ISSUE THREAD

**Issue by Nikita-W** [Faboslav/friends-and-foes#83]
### Minecraft version information

1.19.2

### Mod loader information

Fabric

### Mod loader version information

0.14.11

### Mod version information

1.6.3

### Expected Behavior

Waxed & oxidized versions of the lightning rod to function the same as the vanilla lightning rod.

### Actual Behavior

Waxed lightning rod did not attract lightning, buildings were burned instead.
I tested all the versions of the lightning rod and the only one which was struck by lightning was the vanilla lightning rod.

### Reproduction Steps

1. Place any variety of lightning rod added by this mod.
2. Set weather to thunder.
4. Lightning will not strike the modded lightning rod.

**Comment by Emily8914** [comment]
I was able to reproduce the issue with only F&F loaded in 1.19.2 Fabric edition, following the steps provided.

https://user-images.githubusercontent.com/121458969/209581304-cdca006a-d05e-48f5-a532-e0fd274e951f.mp4

**Comment by Faboslav** [comment]
Hello, thanks for the report and video, i checked it and it is not implemented, i think i will be able to release fix sometime tommorow (it is almost night for me right now).

**Comment by Faboslav** [comment]
Should be resolved with https://github.com/Faboslav/friends-and-foes/releases/tag/mc1.19.2-1.6.6, it will be available on curseforge and modrinth shortly after.
