### ISSUE TITLE
Iceologer should only cast one spell at a time

### ISSUE THREAD

**Issue by kristibektashi** [Faboslav/friends-and-foes#88]
### Minecraft version information

1.19.2

### Mod loader information

Forge

### Mod loader version information

43.2.1

### Mod version information

1.6.7

### Expected Behavior

The iceologer seems to have 2 spells, 1 that directly freezes the player (or other target), and another that spawns an ice chunk on top of the target. Other illagers (e.g. Evoker/Illusioner) only cast 1 spell at a time. Therefore, it makes sense to assume that the Iceologer will behave the same

### Actual Behavior

However, the iceologer seems to both freeze the player and spawn an ice chunk on top of them at the same time, which is inconsistent with other Illagers.

### Reproduction Steps

1. Spawn an Iceologer (or find one)
2. Switch to Survival mode and let the Illusioner attack you
3. Observe how the player freezes and an ice chunk spawns on top of them at the same time

### Screenshots & files

![2023-01-17_00 08 33](https://user-images.githubusercontent.com/40217426/212772688-518fa59f-0532-4d43-902c-14a204dd0dc8.png)

**Comment by Faboslav** [comment]
It is not really inconsistent as it is two separate spells, just short on the cooldown he firstly summon the ice chunk, but with an initial animation and all the things and then he has time for the second spell right after that, same logic is in the original illusioner code, he can blind you(with the hard difficulty on) and do the other spell right away.

**Comment by Faboslav** [comment]
Also important technicality of it is that:
- "Summon ice chunk" cast time is 30 ticks, then cooldown is 220 ticks
- "Slow target" cast time is 20 ticks,  then cooldown is 220 ticks
(20 ticks = 1 sec)

**Comment by kristibektashi** [comment]
> Also important technicality of it is that:
> 
>     * "Summon ice chunk" cast time is 30 ticks, then cooldown is 220 ticks
> 
>     * "Slow target" cast time is 20 ticks,  then cooldown is 220 ticks
>       (20 ticks = 1 sec)

This should be on the iceologer page on the Wiki instead of "TBD"

**Comment by Faboslav** [comment]
I agree, i will try to fill the missing wiki pages as soon as possible :).
