### ISSUE TITLE
Copper Golem is passive even though wiki page says it's neutral

### ISSUE THREAD

**Issue by kristibektashi** [Faboslav/friends-and-foes#89]
### Minecraft version information

1.19,2

### Mod loader information

Fabric

### Mod loader version information

43.2.1

### Mod version information

1.6.7

### Expected Behavior

The wiki page for the Copper Golem says that it is a neutral mob. Therefore I expect it to fight back when I punch it

### Actual Behavior

However, it doesn't fight back

### Reproduction Steps

1. Spawn Copper Golem
2. Go to survival mode
3. Attack the copper golem
4. Observe how it doesn't fight back

**Comment by Faboslav** [comment]
Fixed, thanks :).
