### ISSUE TITLE
Different recipe for a copper button

### ISSUE THREAD

**Issue by lanalancia** [Faboslav/friends-and-foes#9]
**Is your feature request related to a problem? Please describe.**
I've installed this mod with a Tech Reborn and Industrial Revolution. Both mods have a copper nuggets recipe, which looks like this
![image](https://user-images.githubusercontent.com/96468948/148652497-270e9f09-4122-4f9d-93d2-4e082e821ba8.png)

Meanwhile Friends and Foes have same recipe for a copper button:
![image](https://user-images.githubusercontent.com/96468948/148652524-22e25883-1ed2-470d-af07-84de3e9bf64a.png)
That is why i can't get a copper nuggets

**Describe the solution you'd like**
I think a different recipe for a copper button can make solve this conflict without making much impact on a people, who playing Friends and Foes only. My suggestion is making a copper button by mixing a copper and a different button:
![image](https://user-images.githubusercontent.com/96468948/148652606-700a837d-975b-4312-ac4a-b60fcc06087f.png)

**Describe alternatives you've considered**
It's still possible to make a copper nuggets as a biproduct in an industrial centrifuge or in an industrial grinder, but those are a high tech expensive devices. Meanwhile an item i need a copper nuggets for is a low tech servo for an item pipes.

**Comment by Faboslav** [comment]
Hello, I've been thinking about this for a while now, i know that my crafting recipe is probably the most vanilla friendly, but as you say different recipe will solve conflicts thus compatibility with other mods.

Would recipe change from one `Copper Ingot` to from two `Copper Ingots` solve this conflict as well?

**Comment by lanalancia** [comment]
Just checked on two different modpacks, the two `Copper Ingots` is fine.
![image](https://user-images.githubusercontent.com/96468948/148675574-063d9d14-9771-4e0f-9021-df6ab337bd50.png)

**Comment by Faboslav** [comment]
Okay, one more question, does placement matter, or is it fine everywhere?

**Comment by lanalancia** [comment]
The "two copper ingots horysontally" recipe isn't reserved now, but i assume some mods could add a copper pressure plate like that `Iron Pressure Plate` vanilla already have. I would prefer a vertical recipe
![image](https://user-images.githubusercontent.com/96468948/148676427-5002127a-abb0-4d55-a289-b0a3b46cf8cc.png)

**Comment by Faboslav** [comment]
Okay in that case i would probably go with three copper ingots horizontally(because of the shape)? And if that is already taken too, then i will go with two copper ingots vertically. Can you please just do last check for the horizontal shape of three copper ingots?

**Comment by lanalancia** [comment]
![image](https://user-images.githubusercontent.com/96468948/148677661-873192e3-1f18-42f2-bf07-e0649e8ff864.png)
Horizontal shape of three copper ingots is a cable so definitelly not

**Comment by Faboslav** [comment]
Oh god, why is this so difficult :D. I will try to release a minor update today, with this recipe change and a bunch of few other small fixes. Recipe will change to two copper ingots placed horizontally. Thank you, you were very helpful! 

Also you are more than welcome to join the discord server of my mod(https://discord.com/invite/P3tXnXYK) and discuss things here. I am also posting updates(showcases) of my mod there and announcing new releases.

**Comment by lanalancia** [comment]
Yay thank you
