### ISSUE TITLE
Giving Items To Tuff Golems Causes Server Crash

### ISSUE THREAD

**Issue by InfinityGaben** [Faboslav/friends-and-foes#96]
### Minecraft version information

1.19.2

### Mod loader information

Forge

### Mod loader version information

43.2.6

### Mod version information

1.8.0

### Expected Behavior

Tuff golem should hold items.

### Actual Behavior

Servers crash upong giving them items

### Reproduction Steps

Join a server
Make a tuff golem
Give it a item

**Comment by Faboslav** [comment]
Will look into it ASAP.

**Comment by Faboslav** [comment]
I do recommend rollbacking to previous version as i will do 1.8.0 release again due to this critical crash.

**Comment by Jusey1** [comment]
It's not necessarily giving the item that is causing this crash but rather the file "TuffGolemAnimations" is being called to the Server which is causing the crash. (Said file is a client side one that controls the animations). 

Crash happens when the Tuff Golem goes to sleep too btw.

**Comment by Faboslav** [comment]
Release is out again, hopefully without a crash this time :).

**Comment by Jusey1** [comment]
It is still crashing.

**Comment by Faboslav** [comment]
Yes, hopefully now, after new reupload it will be okay.
